// playerbot_weapon_atlas.h - generated by tools/generate_weapon_atlas.py.
// Every weapon family of this world (world.item_proto, +0 vnums), who may
// carry it (the anti-flags), and where a bot can get one: a village merchant
// on a map the bots walk, the common drop of a monster rank and level band
// that stands on such a map, a monster or a chest there, or only on maps no
// bot goes to. Read with world.mob_proto, world.shop and the spawn files of
// every map. Do not edit by hand; run the generator.
#ifndef PLAYERBOT_WEAPON_ATLAS_H
#define PLAYERBOT_WEAPON_ATLAS_H

namespace
{
	const WORD PLAYERBOT_WEAPON_SOURCE_MERCHANT = 0x01;
	const WORD PLAYERBOT_WEAPON_SOURCE_COMMON = 0x02;
	const WORD PLAYERBOT_WEAPON_SOURCE_DROP = 0x04;
	const WORD PLAYERBOT_WEAPON_SOURCE_CHEST = 0x08;
	const WORD PLAYERBOT_WEAPON_SOURCE_STONE = 0x10;
	const WORD PLAYERBOT_WEAPON_SOURCE_ELSEWHERE = 0x20;
	const BYTE PLAYERBOT_WEAPON_CLASS_WARRIOR = 0x01;
	const BYTE PLAYERBOT_WEAPON_CLASS_ASSASSIN = 0x02;
	const BYTE PLAYERBOT_WEAPON_CLASS_SURA = 0x04;
	const BYTE PLAYERBOT_WEAPON_CLASS_SHAMAN = 0x08;

	struct TPlayerBotWeaponFamily
	{
		DWORD dwBaseVnum;   // the +0 of the family
		BYTE bSubType;
		BYTE bLevel;
		BYTE bClassMask;    // PLAYERBOT_WEAPON_CLASS_*
		WORD wSources;      // PLAYERBOT_WEAPON_SOURCE_*
		DWORD dwSourceMob;  // the monster on a bot map with the most spawn points, 0 if none
		WORD wSourceMap;    // where that monster stands, 0 if none
	};

	const TPlayerBotWeaponFamily PLAYERBOT_WEAPON_ATLAS[] = {
		{    10, 0,   0, 0x07, 0x22,     0,   0 },	// Miecz+0 (wspolny,poza)
		{    20, 0,   5, 0x07, 0x03,     0,   0 },	// Dlugi Miecz+0 (kupiec,wspolny)
		{    30, 0,  10, 0x07, 0x06,   104,   1 },	// Sejmitar+0 (wspolny,potwor)
		{    40, 0,  15, 0x07, 0x03,     0,   0 },	// Stozkowy Miecz+0 (kupiec,wspolny)
		{    50, 0,  20, 0x07, 0x06,   104,   1 },	// Szeroki Miecz+0 (wspolny,potwor)
		{    60, 0,  25, 0x07, 0x07,   391,   1 },	// Srebrny Miecz+0 (kupiec,wspolny,potwor)
		{    70, 0,  32, 0x07, 0x06,   603,  64 },	// Miecz Storczykowy+0 (wspolny,potwor)
		{    80, 0,  36, 0x07, 0x07,  5103,   5 },	// Miecz Poltorareczny+0 (kupiec,wspolny,potwor)
		{    90, 0,  40, 0x07, 0x06,   632,  64 },	// Miecz Barbarzyncy+0 (wspolny,potwor)
		{   100, 0,  45, 0x07, 0x2e,  1106,  61 },	// Krwawy Miecz+0 (wspolny,potwor,skrzynia,poza)
		{   110, 0,  50, 0x07, 0x3e,  1106,  61 },	// Wielki Miecz+0 (wspolny,potwor,skrzynia,metin,poza)
		{   120, 0,  55, 0x07, 0x26,  2061,  71 },	// Miecz Lat. Maga+0 (wspolny,potwor,poza)
		{   130, 0,  60, 0x07, 0x26,   904,  61 },	// Pol-ksiezycowy Miecz+0 (wspolny,potwor,poza)
		{   140, 0,  65, 0x07, 0x2c,  2315,  68 },	// Miecz Bojowy+0 (potwor,skrzynia,poza)
		{   150, 0,  65, 0x04, 0x2c,  2315,  68 },	// Miecz Szponu Ducha+0 (potwor,skrzynia,poza)
		{   160, 0,  65, 0x07, 0x24,  2313,  68 },	// Miecz Nimfy+0 (potwor,poza)
		{   170, 0,  70, 0x07, 0x20,     0,   0 },	// Miecz Zadlo+0 (poza)
		{   180, 0,  75, 0x07, 0x20,     0,   0 },	// Zatruty miecz+0 (poza)
		{   190, 0,  75, 0x04, 0x20,     0,   0 },	// Lwi Miecz+0 (poza)
		{   200, 0,  80, 0x04, 0x00,     0,   0 },	// Brzegowe Ostrze+0 (brak)
		{   240, 0,  65, 0x04, 0x2c,  2313,  68 },	// Miecz Egzorcysty+0 (potwor,skrzynia,poza)
		{   250, 0,  70, 0x04, 0x20,     0,   0 },	// Demoniczne Ostrze+0 (poza)
		{   270, 0,  80, 0x07, 0x00,     0,   0 },	// Miecz Trytona+0 (brak)
		{   280, 0,  80, 0x04, 0x00,     0,   0 },	// Swiety Miecz+0 (brak)
		{   290, 0,  30, 0x07, 0x04,   503,   3 },	// Miecz Pelni Ksiezyca+0 (potwor)
		{   460, 0,  87, 0x07, 0x00,     0,   0 },	// Runiczny Miecz+0 (brak)
		{   470, 0,  87, 0x04, 0x00,     0,   0 },	// Klinga Smoczego Kla+0 (brak)
		{  1000, 1,   0, 0x02, 0x22,     0,   0 },	// Sztylet+0 (wspolny,poza)
		{  1010, 1,  10, 0x02, 0x06,   103,  21 },	// Sztylet Kobry+0 (wspolny,potwor)
		{  1020, 1,  20, 0x02, 0x06,   138,  24 },	// Sztylet Nozycowy+0 (wspolny,potwor)
		{  1030, 1,  32, 0x02, 0x06,  5161,   5 },	// Noz Szczescia+0 (wspolny,potwor)
		{  1040, 1,  36, 0x02, 0x07,   633,  64 },	// Ukaszenie Kota+0 (kupiec,wspolny,potwor)
		{  1050, 1,  40, 0x02, 0x06,   632,  64 },	// Twarz Diabla+0 (wspolny,potwor)
		{  1060, 1,  45, 0x02, 0x2e,  2104,  63 },	// Sztylet Piesci Diab.+0 (wspolny,potwor,skrzynia,poza)
		{  1070, 1,  50, 0x02, 0x3e,  1106,  61 },	// Krwawy Sztylet+0 (wspolny,potwor,skrzynia,metin,poza)
		{  1080, 1,  55, 0x02, 0x26,  2062,  71 },	// Zebrowy Noz+0 (wspolny,potwor,poza)
		{  1090, 1,  60, 0x02, 0x26,  1106,  61 },	// Chakram+0 (wspolny,potwor,poza)
		{  1100, 1,  65, 0x02, 0x2c,  2315,  68 },	// Smoczy Noz+0 (potwor,skrzynia,poza)
		{  1110, 1,  65, 0x02, 0x24,  2313,  68 },	// Noz Blyskawicy+0 (potwor,poza)
		{  1120, 1,  70, 0x02, 0x20,     0,   0 },	// Noz Siamese+0 (poza)
		{  1130, 1,  75, 0x02, 0x20,     0,   0 },	// Skrzydla Demona Chakr.+0 (poza)
		{  1170, 1,  30, 0x02, 0x04,   632,  64 },	// Kozik Czar. Lis.+0 (potwor)
		{  1340, 1,  87, 0x02, 0x00,     0,   0 },	// Kolec Pieciu Elementow+0 (brak)
		{  2000, 2,   0, 0x02, 0x22,     0,   0 },	// Luk+0 (wspolny,poza)
		{  2010, 2,   5, 0x02, 0x03,     0,   0 },	// Dlugi Luk+0 (kupiec,wspolny)
		{  2020, 2,  10, 0x02, 0x06,   104,   1 },	// Kompozytowy Luk+0 (wspolny,potwor)
		{  2030, 2,  15, 0x02, 0x03,     0,   0 },	// Bojowy Luk+0 (kupiec,wspolny)
		{  2040, 2,  20, 0x02, 0x06,   393,   1 },	// Dlugi Luk Jezdzcy+0 (wspolny,potwor)
		{  2050, 2,  25, 0x02, 0x07,   393,   1 },	// Bojowy Luk Jezdzcy+0 (kupiec,wspolny,potwor)
		{  2060, 2,  32, 0x02, 0x06,  5161,   5 },	// Miedziany Luk+0 (wspolny,potwor)
		{  2070, 2,  36, 0x02, 0x07,   633,  64 },	// Luk Czarnych Ruin+0 (kupiec,wspolny,potwor)
		{  2080, 2,  40, 0x02, 0x06,   701,  64 },	// Luk Czerwonego Oka+0 (wspolny,potwor)
		{  2090, 2,  45, 0x02, 0x2e,  1105,  61 },	// Luk Kolczastego Lis.+0 (wspolny,potwor,skrzynia,poza)
		{  2100, 2,  50, 0x02, 0x3e,  2063,  71 },	// Luk z rogu byka+0 (wspolny,potwor,skrzynia,metin,poza)
		{  2110, 2,  55, 0x02, 0x26,  2063,  71 },	// Luk Jednorozca+0 (wspolny,potwor,poza)
		{  2120, 2,  60, 0x02, 0x26,  1303,  65 },	// Olbrz. Skrzydl. Luk+0 (wspolny,potwor,poza)
		{  2130, 2,  65, 0x02, 0x2c,  2313,  68 },	// Boski Luk Moreli+0 (potwor,skrzynia,poza)
		{  2140, 2,  65, 0x02, 0x24,  2315,  68 },	// Olbrz. Luk Zolt. Smoka+0 (potwor,poza)
		{  2150, 2,  30, 0x02, 0x04,   503,   3 },	// Luk Z Rogu Jelenia+0 (potwor)
		{  2160, 2,  80, 0x02, 0x00,     0,   0 },	// Olbrz. Luk Diabla+0 (brak)
		{  2170, 2,  75, 0x02, 0x20,     0,   0 },	// Stalowy Luk Kruka+0 (poza)
		{  2180, 2,  70, 0x02, 0x20,     0,   0 },	// Luk Niebieskiego Smoka+0 (poza)
		{  2190, 2,  38, 0x02, 0x00,     0,   0 },	// Upiorna Kusza+0 (brak)
		{  2370, 2,  87, 0x02, 0x00,     0,   0 },	// Luk Feniksa+0 (brak)
		{  3000, 3,   0, 0x01, 0x22,     0,   0 },	// Glewia+0 (wspolny,poza)
		{  3010, 3,   5, 0x01, 0x03,     0,   0 },	// Wlocznia+0 (kupiec,wspolny)
		{  3020, 3,  10, 0x01, 0x02,     0,   0 },	// Gilotynowe Ostrze+0 (wspolny)
		{  3030, 3,  15, 0x01, 0x03,     0,   0 },	// Pajecza Wlocznia+0 (kupiec,wspolny)
		{  3040, 3,  20, 0x01, 0x06,   393,   1 },	// Gizarma+0 (wspolny,potwor)
		{  3050, 3,  25, 0x01, 0x03,     0,   0 },	// Kosa Bojowa+0 (kupiec,wspolny)
		{  3060, 3,  32, 0x01, 0x06,  5161,   5 },	// Trojzab+0 (wspolny,potwor)
		{  3070, 3,  36, 0x01, 0x07,   504,   3 },	// Halabarda+0 (kupiec,wspolny,potwor)
		{  3080, 3,  40, 0x01, 0x06,   633,  64 },	// Olbrz. Topor+0 (wspolny,potwor)
		{  3090, 3,  45, 0x01, 0x2e,  2064,  71 },	// Lodowa Iglica+0 (wspolny,potwor,skrzynia,poza)
		{  3100, 3,  50, 0x01, 0x2e,  2064,  71 },	// Miecz Dwunastu Duchow+0 (wspolny,potwor,skrzynia,poza)
		{  3110, 3,  55, 0x01, 0x26,  2064,  71 },	// Ostrze Zbawienia+0 (wspolny,potwor,poza)
		{  3120, 3,  60, 0x01, 0x26,  2064,  71 },	// Zabojca Lwow+0 (wspolny,potwor,poza)
		{  3130, 3,  65, 0x01, 0x0c,  2315,  68 },	// Partyzana+0 (potwor,skrzynia)
		{  3140, 3,  65, 0x01, 0x24,  2313,  68 },	// Magnetyczne Ostrze+0 (potwor,poza)
		{  3150, 3,  70, 0x01, 0x20,     0,   0 },	// Zlodziej Dusz+0 (poza)
		{  3160, 3,  75, 0x01, 0x00,     0,   0 },	// Miecz Zalu+0 (brak)
		{  3190, 3,  87, 0x01, 0x00,     0,   0 },	// Ostrze Slonca+0 (brak)
		{  3210, 3,  30, 0x01, 0x04,   702,  64 },	// Ostrze Z Czerw. Stali+0 (potwor)
		{  4000, 1,   5, 0x02, 0x03,     0,   0 },	// Amija+0 (kupiec,wspolny)
		{  4010, 1,  15, 0x02, 0x07,   103,  21 },	// Dziewiec Ostrzy+0 (kupiec,wspolny,potwor)
		{  4020, 1,  25, 0x02, 0x07,   405,   3 },	// Krotki Noz+0 (kupiec,wspolny,potwor)
		{  4040, 1,  80, 0x02, 0x00,     0,   0 },	// Bezduszny Noz+0 (brak)
		{  5000, 4,  10, 0x08, 0x22,     0,   0 },	// Miedziany Dzwon+0 (wspolny,poza)
		{  5010, 4,  15, 0x08, 0x07,   109,  21 },	// Srebrny Dzwon+0 (kupiec,wspolny,potwor)
		{  5020, 4,  20, 0x08, 0x02,     0,   0 },	// Zloty Dzwon+0 (wspolny)
		{  5030, 4,  32, 0x08, 0x06,   404,   3 },	// Jadeitowy Dzwon+0 (wspolny,potwor)
		{  5040, 4,  36, 0x08, 0x07,   404,   3 },	// Dzwon Fontanny+0 (kupiec,wspolny,potwor)
		{  5050, 4,  40, 0x08, 0x0e,   631,  64 },	// Morelowy Dzwon+0 (wspolny,potwor,skrzynia)
		{  5060, 4,  50, 0x08, 0x3e,  2065,  71 },	// Magiczny Dzwon+0 (wspolny,potwor,skrzynia,metin,poza)
		{  5070, 4,  55, 0x08, 0x26,  2004,  63 },	// Zloty Robaczy Dzwon+0 (wspolny,potwor,poza)
		{  5080, 4,  60, 0x08, 0x26,  2065,  71 },	// Stalowy Robaczy Dzwon+0 (wspolny,potwor,poza)
		{  5090, 4,  65, 0x08, 0x24,  2315,  68 },	// Dzwon Burzowego Ptaka+0 (potwor,poza)
		{  5100, 4,  65, 0x08, 0x2c,  2313,  68 },	// Dzwon Nieba I Ziemi+0 (potwor,skrzynia,poza)
		{  5110, 4,  30, 0x08, 0x04,  2104,  63 },	// Antyczny Dzwon+0 (potwor)
		{  5120, 4,  75, 0x08, 0x20,     0,   0 },	// Bambusowy Dzwon+0 (poza)
		{  5130, 4,  70, 0x08, 0x20,     0,   0 },	// Dzwon Smierci+0 (poza)
		{  5140, 4,  52, 0x08, 0x00,     0,   0 },	// Smoczy Dzwon+0 (brak)
		{  5150, 4,  52, 0x08, 0x00,     0,   0 },	// Hibiskusowy Dzwon+0 (brak)
		{  5330, 4,  80, 0x08, 0x00,     0,   0 },	// Dzwon Szczeki Smoka+0 (brak)
		{  5340, 4,  87, 0x08, 0x00,     0,   0 },	// Dzwon Smoczego Ducha+0 (brak)
		{  7000, 5,   0, 0x08, 0x22,     0,   0 },	// Wachlarz+0 (wspolny,poza)
		{  7010, 5,   5, 0x08, 0x03,     0,   0 },	// Zelazny Wachlarz+0 (kupiec,wspolny)
		{  7020, 5,  10, 0x08, 0x02,     0,   0 },	// Wachlarz Czarn. Tygr.+0 (wspolny)
		{  7030, 5,  15, 0x08, 0x07,   109,  21 },	// Zurawi Wachlarz+0 (kupiec,wspolny,potwor)
		{  7040, 5,  20, 0x08, 0x06,   131,  44 },	// Pawi Wachlarz+0 (wspolny,potwor)
		{  7050, 5,  25, 0x08, 0x07,   405,   3 },	// Wodny Wachlarz+0 (kupiec,wspolny,potwor)
		{  7060, 5,  32, 0x08, 0x06,  5161,   5 },	// Kamienny Wachlarz+0 (wspolny,potwor)
		{  7070, 5,  36, 0x08, 0x07,   405,   3 },	// Oceaniczny Wachlarz+0 (kupiec,wspolny,potwor)
		{  7080, 5,  40, 0x08, 0x06,   631,  64 },	// Zadlowy Wachlarz+0 (wspolny,potwor)
		{  7090, 5,  45, 0x08, 0x0c,  1105,  61 },	// Wachlarz Feniksa+0 (potwor,skrzynia)
		{  7100, 5,  50, 0x08, 0x1c,  2003,  63 },	// Potrojny Wachlarz+0 (potwor,skrzynia,metin)
		{  7110, 5,  55, 0x08, 0x00,     0,   0 },	// Brwisty Wachlarz+0 (brak)
		{  7120, 5,  60, 0x08, 0x04,  1305,  65 },	// Czarny Slon. Wachlarz+0 (potwor)
		{  7130, 5,  65, 0x08, 0x24,  2315,  68 },	// Niebian. Ptasi Wachl.+0 (potwor,poza)
		{  7140, 5,  65, 0x08, 0x2c,  2313,  68 },	// Wachlarz Zbawienia+0 (potwor,skrzynia,poza)
		{  7150, 5,  70, 0x08, 0x20,     0,   0 },	// Ekstazyjny Wachlarz+0 (poza)
		{  7160, 5,  30, 0x08, 0x04,  2104,  63 },	// Wachlarz Jes. Wiatru+0 (potwor)
		{  7180, 5,  75, 0x08, 0x00,     0,   0 },	// Wachlarz 8 Trigramow+0 (brak)
		{  7190, 5,  80, 0x08, 0x00,     0,   0 },	// Wachlarz Demona+0 (brak)
		{  7200, 7,   0, 0x0f, 0x00,     0,   0 },	// Lanca+0 (brak)
		{  7370, 5,  87, 0x08, 0x00,     0,   0 },	// Wachlarz Lezac. Smoka+0 (brak)
	};
}

#endif
