// MT2009_PLUS_AREZZO_COSTUME_SETS_V2 (generated by client-patches/client-2.0.30/tools/azcostume/gen_azcostume_server.py from
// azcostume_items.json - do not edit by hand): the Arezzo costume sets' items (213) are for sale only
// while the Arezzo module is on - the event flag mt2009_arezzo_closed (1 = off), the switch
// playerbot_arezzo.h follows. Read by the engine's ItemShop (server-patches/azcostume, (ishop-list) / (ishop-buy)):
// CItemShopManager::CanSendItem leaves the line out of the window, BuyItem refuses it) and by the
// bots' catalogue (playerbot_itemshop.h, which includes this file exactly once). The item rows
// stay in item_proto: what a player already holds keeps working.
#ifndef __INC_MT2009_PLUS_AREZZO_COSTUMES_H__
#define __INC_MT2009_PLUS_AREZZO_COSTUMES_H__

#include <algorithm>
#include "questmanager.h"

namespace mt2009_arezzo_costumes
{
	const DWORD VNUMS[] = {
		40600, 40601, 40602, 40603, 40604, 40605, 40700, 40701, 40702, 40703, 40704, 40705,
		40710, 40711, 40712, 40713, 40714, 40715, 40800, 40801, 40802, 40803, 40804, 40805,
		40810, 40811, 40812, 40813, 40814, 40815, 40820, 40821, 40822, 40823, 40824, 40825,
		40830, 40831, 40832, 40833, 40834, 40835, 40850, 40851, 40852, 40853, 40854, 40855,
		40860, 40861, 40862, 40863, 40864, 40865, 40870, 40871, 40872, 40873, 40874, 40875,
		40880, 40881, 40882, 40883, 40884, 40885, 40900, 40901, 40902, 40903, 40904, 40905,
		40910, 40911, 40912, 40913, 40914, 40915, 40920, 40921, 40922, 40923, 40924, 40925,
		40940, 40941, 40942, 40943, 40944, 40945, 40950, 40951, 40952, 40953, 40954, 40955,
		40970, 40971, 40972, 40973, 40974, 40975, 40980, 40981, 40982, 40983, 40984, 40985,
		40990, 40991, 40992, 40993, 40994, 40995, 42900, 42901, 42904, 42905, 42908, 42909,
		42924, 42925, 42926, 42927, 42928, 42929, 42932, 42933, 42934, 42935, 42936, 42937,
		42938, 42939, 42940, 42941, 42942, 42943, 42944, 42945, 42948, 42949, 42950, 42951,
		42952, 42953, 42954, 42955, 42958, 42959, 42960, 42961, 42962, 42963, 45900, 45901,
		45904, 45905, 45908, 45909, 45924, 45925, 45926, 45927, 45928, 45929, 45932, 45933,
		45934, 45935, 45936, 45937, 45938, 45939, 45940, 45941, 45942, 45943, 45944, 45945,
		45948, 45949, 45950, 45951, 45952, 45953, 45954, 45955, 45958, 45959, 45960, 45961,
		45962, 45963, 85200, 85201, 85202, 85203, 85204, 85206, 85207, 85208, 85209, 85210,
		85211, 85212, 85214, 85215, 85216, 85217, 85219, 85220, 85221,
	};

	inline bool IsItem(DWORD vnum)
	{
		return std::binary_search(VNUMS, VNUMS + sizeof(VNUMS) / sizeof(VNUMS[0]), vnum);
	}

	inline bool ModuleClosed()
	{
		return quest::CQuestManager::instance().GetEventFlag("mt2009_arezzo_closed") > 0;
	}
}

// The engine's side (itemshop_manager.cpp declares it): an Arezzo set item while the module is off.
bool Mt2009PlusArezzoCostumeLocked(DWORD vnum)
{
	return mt2009_arezzo_costumes::IsItem(vnum) && mt2009_arezzo_costumes::ModuleClosed();
}

#endif
