#ifndef __INC_METIN_II_LENGTH_H__
#define __INC_METIN_II_LENGTH_H__

#include "CommonDefines.h"

#define WORD_MAX 0xffff

enum LongData : long long {
	//LIMIT_GOLD
	GOLD_MAX = 2000000000LL,
};

enum EMisc
{
	MAX_HOST_LENGTH = 15,
	IP_ADDRESS_LENGTH = 15,
	LOGIN_MAX_LEN = 30,
	PASSWD_MAX_LEN = 16,
	HWID_MAX_LEN = 255,
#ifdef ENABLE_PLAYER_PER_ACCOUNT5
	PLAYER_PER_ACCOUNT = 5,
#else
	PLAYER_PER_ACCOUNT = 4,
#endif
	ACCOUNT_STATUS_MAX_LEN = 8,
	CHARACTER_NAME_MAX_LEN = 24,
	PLAYER_NAME_MAX_LEN = 14,
	SHOP_SIGN_MAX_LEN = 32,
	INVENTORY_PAGE_COLUMN = 5, // 5 (default)
	INVENTORY_PAGE_ROW = 9, // 9 (default)
	INVENTORY_PAGE_SIZE = INVENTORY_PAGE_COLUMN * INVENTORY_PAGE_ROW,
#ifdef ENABLE_EXTEND_INVEN_SYSTEM
	// Four normal bag pages.  The horse inventory remains a separate fifth
	// page and therefore starts at INVENTORY_DEFAULT_MAX_NUM (cell 180).
	INVENTORY_DEFAULT_PAGE_COUNT = 4,
	HORSE_INVENTORY_PAGE = 1,
	INVENTORY_PAGE_COUNT = INVENTORY_DEFAULT_PAGE_COUNT + HORSE_INVENTORY_PAGE,
#else
	INVENTORY_PAGE_COUNT = 2, // 2 (default)
#endif
	INVENTORY_DEFAULT_MAX_NUM = INVENTORY_PAGE_SIZE * INVENTORY_DEFAULT_PAGE_COUNT, // 90 (default)
	INVENTORY_MAX_NUM = INVENTORY_PAGE_SIZE * INVENTORY_PAGE_COUNT, // 90 (default)
	ABILITY_MAX_NUM = 50,
	EMPIRE_MAX_NUM = 4,
	BANWORD_MAX_LEN = 24,
	SOCIAL_ID_MAX_LEN = 18,

	GUILD_NAME_MAX_LEN = 14,

	SHOP_GUEST_ITEM_MAX_NUM = 18,

	CHAT_MAX_LEN = 512,

	QUICKSLOT_MAX_COUNT_PER_LINE = 10,
	QUICKSLOT_MAX_LINE = 4,
	QUICKSLOT_MAX_NUM = QUICKSLOT_MAX_LINE * QUICKSLOT_MAX_COUNT_PER_LINE,

	JOURNAL_MAX_NUM = 2,

	QUERY_MAX_LEN = 8192,

	FILE_MAX_LEN = 128,

	PLAYER_EXP_TABLE_MAX = 120,
	PLAYER_MAX_LEVEL_CONST = 250,

	GUILD_MAX_LEVEL = 20,
	MOB_MAX_LEVEL = 100,

	ATTRIBUTE_MAX_VALUE = 20,
	CHARACTER_PATH_MAX_NUM = 64,
	SKILL_MAX_NUM = 265,
	SKILLBOOK_LEARN_DELAY = 21 * 3600,
	SKILL_MAX_LEVEL = 40,

	APPLY_NAME_MAX_LEN = 32,
	EVENT_FLAG_NAME_MAX_LEN = 32,

	MOB_SKILL_MAX_NUM = 5,

	WHISPER_MINIMUM_LEVEL = 10,

	DRAGON_SOUL_BOX_SIZE = 32,
	DRAGON_SOUL_BOX_COLUMN_NUM = 8,
	DRAGON_SOUL_BOX_ROW_NUM = DRAGON_SOUL_BOX_SIZE / DRAGON_SOUL_BOX_COLUMN_NUM,
	DRAGON_SOUL_REFINE_GRID_SIZE = 15,
	MAX_AMOUNT_OF_MALL_BONUS = 20,

	WEAR_MAX_NUM = 32,

	//LIMIT_GOLD
	EXCHANGE_GOLD_MAX = 100000000,

	SHOP_DEFAULT_WIDTH = 5,
	SHOP_DEFAULT_HEIGHT = 8,

	SHOP_HOST_ITEM_MAX_NUM = SHOP_DEFAULT_WIDTH * SHOP_DEFAULT_HEIGHT,

	SHOP_PLAYER_WIDTH = SHOP_DEFAULT_WIDTH * 2,
	SHOP_PLAYER_HEIGHT = SHOP_DEFAULT_HEIGHT,

	SHOP_PLAYER_HOST_ITEM_MAX_NUM = SHOP_PLAYER_WIDTH * SHOP_PLAYER_HEIGHT,
	SHOP_PRICELIST_MAX_NUM = SHOP_PLAYER_HOST_ITEM_MAX_NUM,

	SHOP_PLAYER_FIRST_PAGE_X_START = 0,
	SHOP_PLAYER_FIRST_PAGE_X_END = SHOP_DEFAULT_WIDTH - 1,
	SHOP_PLAYER_FIRST_PAGE_Y_START = 0,
	SHOP_PLAYER_FIRST_PAGE_Y_END = SHOP_DEFAULT_HEIGHT - 1,

	SHOP_PLAYER_PREMIUM_X_START = 5,
	SHOP_PLAYER_PREMIUM_X_END = SHOP_PLAYER_WIDTH - 1,
	SHOP_PLAYER_PREMIUM_Y_START = 4,
	SHOP_PLAYER_PREMIUM_Y_END = SHOP_PLAYER_HEIGHT - 1,

	SHOP_PLAYER_LOCKED_X_START = 5,
	SHOP_PLAYER_LOCKED_X_END = SHOP_PLAYER_WIDTH - 1,
	SHOP_PLAYER_LOCKED_Y_START = 0,
	SHOP_PLAYER_LOCKED_Y_END = SHOP_PLAYER_PREMIUM_Y_START - 1,

#ifdef ENABLE_IKASHOP_RENEWAL
	OFFLINE_SHOP_NAME_MAX_LEN = 32,
	OFFLINESHOP_DURATION_MAX_MINUTES = 8 * 24 * 60,
	OFFLINESHOP_AUCTION_DURATION = 3 * 24 * 60,
	OFFLINESHOP_MAX_SEARCH_RESULT = 2500,
	OFFLINESHOP_SECONDS_PER_SEARCH = 5,
	OFFLINESHOP_SECONDS_PER_OFFER = 5,
	OFFLINESHOP_RESTORE_DURATION_COST = 1000000,
	OFFLINESHOP_MIN_OFFER_PERCENTAGE = 30,
	OFFLINESHOP_MAX_WEIGHT_PER_PLAYER = 2500,
	OFFLINESHOP_MAX_PENDING_OFFERS = 30,
	OFFLINESHOP_TIME_OPTION_MAX = 6,
	OFFLINESHOP_DEFAULT_TAX_PCT = 5,

	OFFLINESHOP_SAFEBOX_WIDTH = SHOP_PLAYER_WIDTH,
	OFFLINESHOP_SAFEBOX_HEIGHT = SHOP_PLAYER_HEIGHT,
	OFFLINESHOP_MAX_SAFEBOX_SIZE = OFFLINESHOP_SAFEBOX_WIDTH * OFFLINESHOP_SAFEBOX_HEIGHT,

	OFFLINESHOP_MYSHOP_TARGET_INDEX = 50,
	OFFLINESHOP_START_TARGET_INDEX = 51,
	OFFLINESHOP_END_TARGET_INDEX = 200,

#ifdef EXTEND_IKASHOP_PRO
	OFFLINESHOP_NOTIFICATION_FORMAT_LEN = 40,
#endif
#endif

#ifdef ENABLE_CHEQUE_SYSTEM
	CHEQUE_MAX = 1000,
	CHEQUE_VNUM = 2,
	YANG_PER_CHEQUE = 100000000,
#endif
	//END_LIMIT_GOLD

	SHOP_TAB_NAME_MAX = 32,
	SHOP_TAB_COUNT_MAX = 3,

	ITEMSHOP_SINGLE_PACKET_MAX_ITEMS = 128,

	BELT_INVENTORY_SLOT_WIDTH = 4,
	BELT_INVENTORY_SLOT_HEIGHT= 4,

	BELT_INVENTORY_SLOT_COUNT = BELT_INVENTORY_SLOT_WIDTH * BELT_INVENTORY_SLOT_HEIGHT,

	SAFEBOX_PAGE_WIDTH = 5,
	SAFEBOX_PAGE_HEIGHT = 9,
	SAFEBOX_PAGE_COUNT = 3,
	SAFEBOX_PREMIUM_PAGE_COUNT = 1,
	SAFEBOX_MAX_NUM = SAFEBOX_PAGE_WIDTH * SAFEBOX_PAGE_HEIGHT * SAFEBOX_PAGE_COUNT,
	SAFEBOX_PASSWORD_MAX_LEN = 6,

	DUNGEON_INSTANCE_LIFETIME = 300,

	CODE_VOUCHER_MAX_LEN = 20,
};

enum EWearPositions
{
	WEAR_BODY,		// 0
	WEAR_HEAD,		// 1
	WEAR_FOOTS,		// 2
	WEAR_WRIST,		// 3
	WEAR_WEAPON,	// 4
	WEAR_NECK,		// 5
	WEAR_EAR,		// 6
	WEAR_UNIQUE1,	// 7
	WEAR_UNIQUE2,	// 8
	WEAR_ARROW,		// 9
	WEAR_SHIELD,	// 10
    WEAR_ABILITY1,  // 11
    WEAR_ABILITY2,  // 12
    WEAR_ABILITY3,  // 13
    WEAR_ABILITY4,  // 14
    WEAR_ABILITY5,  // 15
    WEAR_ABILITY6,  // 16
    WEAR_ABILITY7,  // 17
    WEAR_ABILITY8,  // 18
	WEAR_COSTUME_BODY,	// 19
	WEAR_COSTUME_HAIR,	// 20

#ifdef ENABLE_MOUNT_COSTUME_SYSTEM
	WEAR_COSTUME_MOUNT,	// 21
#endif

#ifdef ENABLE_ACCE_COSTUME_SYSTEM
	WEAR_COSTUME_ACCE,	// 22
#endif

	WEAR_BELT,			// 23

#ifdef ENABLE_WEAPON_COSTUME_SYSTEM
	WEAR_COSTUME_WEAPON,// 24
#endif

	WEAR_PENDANT,		// 25
	WEAR_GLOVE,			// 26

	WEAR_MAX = 32
};

enum EDragonSoulDeckType
{
	DRAGON_SOUL_DECK_0,
	DRAGON_SOUL_DECK_1,
	DRAGON_SOUL_DECK_MAX_NUM = 2,

	DRAGON_SOUL_DECK_RESERVED_MAX_NUM = 3,
};

enum ESex
{
	SEX_MALE,
	SEX_FEMALE
};

enum EDirection
{
	DIR_NORTH,
	DIR_NORTHEAST,
	DIR_EAST,
	DIR_SOUTHEAST,
	DIR_SOUTH,
	DIR_SOUTHWEST,
	DIR_WEST,
	DIR_NORTHWEST,
	DIR_MAX_NUM
};

#define ABILITY_MAX_LEVEL	10

enum EAbilityDifficulty
{
	DIFFICULTY_EASY,
	DIFFICULTY_NORMAL,
	DIFFICULTY_HARD,
	DIFFICULTY_VERY_HARD,
	DIFFICULTY_NUM_TYPES
};

enum EAbilityCategory
{
	CATEGORY_PHYSICAL,
	CATEGORY_MENTAL,
	CATEGORY_ATTRIBUTE,
	CATEGORY_NUM_TYPES
};

enum EJobs
{
	JOB_WARRIOR,
	JOB_ASSASSIN,
	JOB_SURA,
	JOB_SHAMAN,
#ifdef ENABLE_WOLFMAN_CHARACTER
	JOB_WOLFMAN,
#endif
	JOB_MAX_NUM
};

enum EClassSkillGroups
{
	NO_GROUP = 0,
	WARRIOR_BODY = 1,
	WARRIOR_MENTAL = 2,

	NINJA_DAGGER = 1,
	NINJA_ARCHER = 2,

	SURA_WEAPON_MASTER = 1,
	SURA_BLACK_MAGIC = 2,

	SHAMAN_DRAGON = 1,
	SHAMAN_HEALER = 2,
};

enum ESkillGroups
{
	SKILL_GROUP_MAX_NUM = 2,
};

enum ERaceFlags
{
	RACE_FLAG_ANIMAL	= (1 << 0),
	RACE_FLAG_UNDEAD	= (1 << 1),
	RACE_FLAG_DEVIL		= (1 << 2),
	RACE_FLAG_HUMAN		= (1 << 3),
	RACE_FLAG_ORC		= (1 << 4),
	RACE_FLAG_MILGYO	= (1 << 5),
	RACE_FLAG_INSECT	= (1 << 6),
	RACE_FLAG_FIRE		= (1 << 7),
	RACE_FLAG_ICE		= (1 << 8),
	RACE_FLAG_DESERT	= (1 << 9),
	RACE_FLAG_TREE		= (1 << 10),
	RACE_FLAG_ATT_ELEC	= (1 << 11),
	RACE_FLAG_ATT_FIRE	= (1 << 12),
	RACE_FLAG_ATT_ICE	= (1 << 13),
	RACE_FLAG_ATT_TEMPLE = (1 << 14),
	RACE_FLAG_ATT_EARTH	= (1 << 15),
	RACE_FLAG_ATT_DARK	= (1 << 16),
	RACE_FLAG_CZ		= (1 << 17), // 1<<11 official
};

enum EMoveFuncType
{
	FUNC_WAIT,
	FUNC_MOVE,
	FUNC_ATTACK,
	FUNC_COMBO,
	FUNC_MOB_SKILL,
	FUNC_EMOTION,
	FUNC_MAX_NUM,
	FUNC_SKILL = 0x80,
};

enum ELoads
{
	LOAD_NONE,
	LOAD_LIGHT,
	LOAD_NORMAL,
	LOAD_HEAVY,
	LOAD_MASSIVE
};

enum
{
	QUICKSLOT_TYPE_NONE,
	QUICKSLOT_TYPE_ITEM,
	QUICKSLOT_TYPE_SKILL,
	QUICKSLOT_TYPE_COMMAND,
	QUICKSLOT_TYPE_MAX_NUM,
};

enum EParts
{
	PART_MAIN,
	PART_WEAPON,
	PART_HEAD,
	PART_HAIR,
#ifdef ENABLE_ACCE_COSTUME_SYSTEM
	PART_ACCE,
#endif
	PART_MAX_NUM,
	PART_WEAPON_SUB,
};

enum EChatType
{
	CHAT_TYPE_TALKING,
	CHAT_TYPE_INFO,
	CHAT_TYPE_NOTICE,
	CHAT_TYPE_PARTY,
	CHAT_TYPE_GUILD,
	CHAT_TYPE_COMMAND,
	CHAT_TYPE_SHOUT,
	CHAT_TYPE_WHISPER,
	CHAT_TYPE_BIG_NOTICE,
	CHAT_TYPE_MONARCH_NOTICE,
#ifdef ENABLE_DICE_SYSTEM
	CHAT_TYPE_DICE_INFO, //11
#endif
	CHAT_TYPE_TRADE,
	CHAT_TYPE_FANCY_NOTICE,
	CHAT_TYPE_GAMEMASTER_NOTICE,
	// MT2009_PLUS_ZODIAC_V1 (Autor: Digi Rasta, Swiatynia Zodiaku): the mission board lines, 13..15 as on the server
	CHAT_TYPE_MISSION,
	CHAT_TYPE_SUB_MISSION,
	CHAT_TYPE_CLEAR_MISSION,
	CHAT_TYPE_MAX_NUM,

	CHAT_TYPE_SPECIAL_INTERNAL=39,
};

enum EWhisperType
{
	WHISPER_TYPE_NORMAL		= 0,
	WHISPER_TYPE_NOT_EXIST		= 1,
	WHISPER_TYPE_TARGET_BLOCKED	= 2,
	WHISPER_TYPE_SENDER_BLOCKED	= 3,
	WHISPER_TYPE_ERROR		= 4,
	WHISPER_TYPE_GM			= 5,
	WHISPER_TYPE_MYSHOP     = 6,
	WHISPER_TYPE_MESSENGER_BLOCKED_TARGET = 7,
	WHISPER_TYPE_MESSENGER_BLOCKED_ME = 8,
	WHISPER_TYPE_LOW_LEVEL = 9,
	WHISPER_TYPE_TUTOR = 10,
	WHISPER_TYPE_SYSTEM		= 0xFF
};

enum ECharacterPosition
{
	POSITION_GENERAL,
	POSITION_BATTLE,
	POSITION_DYING,
	POSITION_SITTING_CHAIR,
	POSITION_SITTING_GROUND,
	POSITION_INTRO,
	POSITION_MAX_NUM
};

enum EGMLevels
{
	GM_PLAYER,
	GM_LOW_WIZARD, // tutor
	GM_WIZARD,
	GM_HIGH_WIZARD,
	GM_GOD,
	GM_IMPLEMENTOR,
	GM_DISABLE,
};

enum EMobRank
{
	MOB_RANK_PAWN,
	MOB_RANK_S_PAWN,
	MOB_RANK_KNIGHT,
	MOB_RANK_S_KNIGHT,
	MOB_RANK_BOSS,
	MOB_RANK_KING,
	MOB_RANK_MAX_NUM
};

enum ECharType
{
	CHAR_TYPE_MONSTER,
	CHAR_TYPE_NPC,
	CHAR_TYPE_STONE,
	CHAR_TYPE_WARP,
	CHAR_TYPE_DOOR,
	CHAR_TYPE_BUILDING,
	CHAR_TYPE_PC,
	CHAR_TYPE_POLYMORPH_PC,
	CHAR_TYPE_HORSE,
	CHAR_TYPE_GOTO,
	CHAR_TYPE_AOE,
	CHAR_TYPE_PET,
};

enum EBattleType
{
	BATTLE_TYPE_MELEE,
	BATTLE_TYPE_RANGE,
	BATTLE_TYPE_MAGIC,
	BATTLE_TYPE_SPECIAL,
	BATTLE_TYPE_POWER,
	BATTLE_TYPE_TANKER,
	BATTLE_TYPE_SUPER_POWER,
	BATTLE_TYPE_SUPER_TANKER,
	BATTLE_TYPE_MAX_NUM
};

enum EOnClickEvents
{
	ON_CLICK_NONE,
	ON_CLICK_SHOP,
	ON_CLICK_TALK,
	ON_CLICK_MAX_NUM
};

enum EOnIdleEvents
{
	ON_IDLE_NONE,
	ON_IDLE_GENERAL,
	ON_IDLE_MAX_NUM
};

enum EWindows
{
	RESERVED_WINDOW,
	INVENTORY,
	EQUIPMENT,
	SAFEBOX,
	MALL,
	DRAGON_SOUL_INVENTORY,
	BELT_INVENTORY,
	GROUND,
#ifdef ENABLE_IKASHOP_RENEWAL
	IKASHOP_OFFLINESHOP,
	IKASHOP_SAFEBOX,
	IKASHOP_AUCTION,
#endif
	WINDOW_TYPE_MAX,

	HORSE_INVENTORY, // not used as seperate window
};

enum EMobSizes
{
	MOBSIZE_RESERVED,
	MOBSIZE_SMALL,
	MOBSIZE_MEDIUM,
	MOBSIZE_BIG
};

enum EAIFlags
{
	AIFLAG_AGGRESSIVE		= (1 << 0),
	AIFLAG_NOMOVE			= (1 << 1),
	AIFLAG_COWARD			= (1 << 2),
	AIFLAG_NOATTACKSHINSU	= (1 << 3),
	AIFLAG_NOATTACKJINNO	= (1 << 4),
	AIFLAG_NOATTACKCHUNJO	= (1 << 5),
	AIFLAG_ATTACKMOB		= (1 << 6),
	AIFLAG_BERSERK			= (1 << 7),
	AIFLAG_STONESKIN		= (1 << 8),
	AIFLAG_GODSPEED			= (1 << 9),
	AIFLAG_DEATHBLOW		= (1 << 10),
	AIFLAG_REVIVE			= (1 << 11),
	//AIFLAG_HEALER			= (1 << 12),
	AIFLAG_IGNORE_LAST_ATTACK = (1 << 12),
	AIFLAG_NO_WANDER = (1 << 13),
	AIFLAG_SEE_OTHER = (1 << 14),
	AIFLAG_RETURN_LAST_ATTACK_POS = (1 << 15),
	AIFLAG_LOOSE_AGGRO_ON_DISTANCE = (1 << 16),
	//AIFLAG_COUNT			= (1 << 13),
	//AIFLAG_NORECOVERY		= (1 << 14),
	//AIFLAG_REFLECT			= (1 << 15),
	//AIFLAG_FALL				= (1 << 16),
	//AIFLAG_VIT				= (1 << 17),
	//AIFLAG_RATTSPEED		= (1 << 18),
	//AIFLAG_RCASTSPEED		= (1 << 19),
	//AIFLAG_RHP_REGEN		= (1 << 20),
	//AIFLAG_TIMEVIT			= (1 << 21),
};

enum EMobStatType
{
	MOB_STATTYPE_POWER,
	MOB_STATTYPE_TANKER,
	MOB_STATTYPE_SUPER_POWER,
	MOB_STATTYPE_SUPER_TANKER,
	MOB_STATTYPE_RANGE,
	MOB_STATTYPE_MAGIC,
	MOB_STATTYPE_MAX_NUM
};

enum EImmuneFlags
{
	IMMUNE_STUN		= (1 << 0),
	IMMUNE_SLOW		= (1 << 1),
	IMMUNE_FALL		= (1 << 2),
	IMMUNE_CURSE	= (1 << 3),
	IMMUNE_POISON	= (1 << 4),
	IMMUNE_TERROR	= (1 << 5),
	IMMUNE_REFLECT	= (1 << 6),
	IMMUNE_ROOT	= (1 << 7),
};

enum EMobEnchants
{
	MOB_ENCHANT_CURSE,
	MOB_ENCHANT_SLOW,
	MOB_ENCHANT_POISON,
	MOB_ENCHANT_STUN,
	MOB_ENCHANT_CRITICAL,
	MOB_ENCHANT_PENETRATE,
	MOB_ENCHANT_FIRE,
	MOB_ENCHANT_ROOT,
#if defined(ENABLE_WOLFMAN_CHARACTER) && !defined(USE_MOB_BLEEDING_AS_POISON)
	MOB_ENCHANT_BLEEDING,
#endif
	MOB_ENCHANTS_MAX_NUM
};

enum EMobResists
{
	MOB_RESIST_SWORD,
	MOB_RESIST_TWOHAND,
	MOB_RESIST_DAGGER,
	MOB_RESIST_BELL,
	MOB_RESIST_FAN,
	MOB_RESIST_BOW,
	MOB_RESIST_FIRE,
	MOB_RESIST_ELECT,
	MOB_RESIST_MAGIC,
	MOB_RESIST_WIND,
	MOB_RESIST_POISON,
#if defined(ENABLE_WOLFMAN_CHARACTER) && !defined(USE_MOB_CLAW_AS_DAGGER)
	MOB_RESIST_CLAW,
#endif
#if defined(ENABLE_WOLFMAN_CHARACTER) && !defined(USE_MOB_BLEEDING_AS_POISON)
	MOB_RESIST_BLEEDING,
#endif
	MOB_RESISTS_MAX_NUM
};

enum
{
	SKILL_ATTR_TYPE_NORMAL = 1,
	SKILL_ATTR_TYPE_MELEE,
	SKILL_ATTR_TYPE_RANGE,
	SKILL_ATTR_TYPE_MAGIC
		/*
		   SKILL_ATTR_TYPE_FIRE,
		   SKILL_ATTR_TYPE_ICE,
		   SKILL_ATTR_TYPE_ELEC,
		   SKILL_ATTR_TYPE_DARK,
		   */
};

enum
{
	SKILL_NORMAL,
	SKILL_MASTER,
	SKILL_GRAND_MASTER,
	SKILL_PERFECT_MASTER,
};

enum EGuildWarType
{
	GUILD_WAR_TYPE_FIELD,
	GUILD_WAR_TYPE_BATTLE,
	GUILD_WAR_TYPE_FLAG,
	GUILD_WAR_TYPE_MAX_NUM
};

enum EGuildWarState
{
	GUILD_WAR_NONE,
	GUILD_WAR_SEND_DECLARE,
	GUILD_WAR_REFUSE,
	GUILD_WAR_RECV_DECLARE,
	GUILD_WAR_WAIT_START,
	GUILD_WAR_CANCEL,
	GUILD_WAR_ON_WAR,
	GUILD_WAR_END,
	GUILD_WAR_OVER,
	GUILD_WAR_RESERVE,

	GUILD_WAR_DURATION = 30*60,
	GUILD_WAR_WIN_POINT = 1000,
	GUILD_WAR_LADDER_HALF_PENALTY_TIME = 12*60*60,
};

enum EAttributeSet
{
	ATTRIBUTE_SET_WEAPON,
	ATTRIBUTE_SET_BODY,
	ATTRIBUTE_SET_WRIST,
	ATTRIBUTE_SET_FOOTS,
	ATTRIBUTE_SET_NECK,
	ATTRIBUTE_SET_HEAD,
	ATTRIBUTE_SET_SHIELD,
	ATTRIBUTE_SET_EAR,
#ifdef ENABLE_ITEM_ATTR_COSTUME
	ATTRIBUTE_SET_COSTUME_BODY,
	ATTRIBUTE_SET_COSTUME_HAIR,
#if defined(ENABLE_ITEM_ATTR_COSTUME) && defined(ENABLE_WEAPON_COSTUME_SYSTEM)
	ATTRIBUTE_SET_COSTUME_WEAPON,
#endif
#endif
#ifdef ENABLE_PENDANT_SYSTEM
	ATTRIBUTE_SET_PENDANT,
#endif
#ifdef ENABLE_GLOVE_SYSTEM
	ATTRIBUTE_SET_GLOVE,
#endif
	ATTRIBUTE_SET_MAX_NUM
};

enum EPrivType
{
	PRIV_NONE,
	PRIV_ITEM_DROP,
	PRIV_GOLD_DROP,
	PRIV_GOLD10_DROP,
	PRIV_EXP_PCT,
	MAX_PRIV_NUM,
};

enum EMoneyLogType
{
	MONEY_LOG_RESERVED,
	MONEY_LOG_MONSTER,
	MONEY_LOG_SHOP,
	MONEY_LOG_REFINE,
	MONEY_LOG_QUEST,
	MONEY_LOG_GUILD,
	MONEY_LOG_MISC,
	MONEY_LOG_MONSTER_KILL,
	MONEY_LOG_DROP,
	MONEY_LOG_TYPE_MAX_NUM,
};

enum EQuestLogType
{
	QUEST_LOG_RESERVED,
	QUEST_LOG_ITEM,
	QUEST_LOG_GOLD,
	QUEST_LOG_EXP,
	QUEST_LOG_LEVEL,
	QUEST_LOG_ALIGNMENT,
	QUEST_LOG_TYPE_MAX_NUM,
};

enum ERequestInfoState
{
	REQUEST_INFO_STATE_NONE,
	REQUEST_INFO_STATE_WAITING,
	REQUEST_INFO_STATE_RECEIVED,
};

enum ERequestInfoType
{
	REQUEST_INFO_RESERVED,
	REQUEST_INFO_DISCORD,
	REQUEST_INFO_HACK,
};

enum EPremiumTypes
{
	PREMIUM_EXP,
	PREMIUM_ITEM,
	PREMIUM_SAFEBOX,
	PREMIUM_AUTOLOOT,
	PREMIUM_FISH_MIND,
	PREMIUM_MARRIAGE_FAST,
	PREMIUM_GOLD,
	PREMIUM_SHOP,
	PREMIUM_MAX_NUM = 9
};

enum SPECIAL_EFFECT
{
	SE_NONE,

	SE_HPUP_RED,
	SE_SPUP_BLUE,
	SE_SPEEDUP_GREEN,
	SE_DXUP_PURPLE,
	SE_CRITICAL,
	SE_PENETRATE,
	SE_BLOCK,
	SE_DODGE,
	SE_CHINA_FIREWORK,
	SE_SPIN_TOP,
	SE_SUCCESS,
	SE_FAIL,
	SE_FR_SUCCESS,
	SE_LEVELUP_ON_14_FOR_GERMANY,
	SE_LEVELUP_UNDER_15_FOR_GERMANY,
	SE_PERCENT_DAMAGE1,
	SE_PERCENT_DAMAGE2,
	SE_PERCENT_DAMAGE3,

	SE_AUTO_HPUP,
	SE_AUTO_SPUP,

	SE_EQUIP_RAMADAN_RING,
	SE_EQUIP_HALLOWEEN_CANDY,
	SE_EQUIP_HAPPINESS_RING,
	SE_EQUIP_LOVE_PENDANT,

	SE_FRESH_WATER,
	SE_FLAME_BLOW,
	SE_DRINK_POTION,
	SE_AOE_TREE_BLOW,
	SE_AOE_GIANT_BLOW,
	SE_ENT_AURA,
	SE_BLOW_POISON,

	SE_BRAVERY_CAPE,

	SE_STEALTH_0,
	SE_STEALTH_1,
	SE_STEALTH_2,
	SE_STEALTH_3,

#ifdef ENABLE_ACCE_COSTUME_SYSTEM
	SE_EFFECT_ACCE_SUCESS_ABSORB,
	SE_EFFECT_ACCE_EQUIP,
#endif
	// MT2009_PLUS_ZODIAC_V1 (Autor: Digi Rasta): the Zodiac effects, in the server's order (first = 39)
	SE_SKILL_DAMAGE_ZONE,
	SE_SKILL_SAFE_ZONE,
	SE_METEOR,
	SE_BEAD_RAIN,
	SE_FALL_ROCK,
	SE_ARROW_RAIN,
	SE_HORSE_DROP,
	SE_EGG_DROP,
	SE_DEAPO_BOOM,
	SE_SKILL_DAMAGE_ZONE_BIG,
	SE_SKILL_DAMAGE_ZONE_MIDDLE,
	SE_SKILL_DAMAGE_ZONE_SMALL,
	SE_SKILL_SAFE_ZONE_BIG,
	SE_SKILL_SAFE_ZONE_MIDDLE,
	SE_SKILL_SAFE_ZONE_SMALL,
};

enum BattleRestricts {
	ATTACK_MELEE_MAX_DISTANCE = 410,
	ATTACK_MELEE_HORSE_MAX_DISTANCE = 900,
	ATTACK_RANGE_MAX_DISTANCE = 2710,

	ATTACK_DISTANCE_SKILL_MAX_DISTANCE = 1100,


	ATTACK_TYPE_NO_WEAPON = 0,
	ATTACK_TYPE_POLYMORPH = 1,
	ATTACK_TYPE_WEAPON = 2,
	ATTACK_TYPE_MOUNT_WEAPON = 3,

	DEFAULT_REAL_ATTACK_SPEED = 5,
	REAL_ATTACK_SPEED_MIN = 150,
	REAL_AVERAGE_ATTACK_SPEED_MIN = 500,

	ATTACK_MAX_VICTIM = 20,
	ATTACK_MAX_DELTA_TIME_COUNT_SINGLE_ATTACK = 30,

	REAL_MOVE_MAX_DELAY_TIME = 3000,
	REAL_MOVE_MAX_DISTANCE = 2050,

	MOVE_AVERAGE_DISTANCE_PER_SECOND_AND_HALF_DELAY = 748,
	MOVE_MAX_DISTANCE_PER_SECOND_AND_HALF_DELAY = 933,
	MOVE_HORSE_AVERAGE_DISTANCE_PER_SECOND_AND_HALF_DELAY = 1220,
	MOVE_HORSE_MAX_DISTANCE_PER_SECOND_AND_HALF_DELAY = 1463,
	MOVE_HORSE_WILDATTACK_SKILL = 1500,

	BLOCK_HACK_DURATION = 3,
	SYNC_HACK_MAX_COUNT = 10,
};

#include "item_length.h"
#include "skill_length.h"

enum EAffectTypes
{
	AFFECT_NONE,

	AFFECT_MOV_SPEED = 200,
	AFFECT_ATT_SPEED,
	AFFECT_ATT_GRADE,
	AFFECT_INVISIBILITY,
	AFFECT_STR,
	AFFECT_DEX,			// 205
	AFFECT_CON,
	AFFECT_INT,
	AFFECT_FISH_MIND_PILL,

	AFFECT_POISON,
	AFFECT_STUN,		// 210
	AFFECT_SLOW,
	AFFECT_DUNGEON_READY,
	AFFECT_DUNGEON_UNIQUE,

	AFFECT_BUILDING,
	AFFECT_REVIVE_INVISIBLE,	// 215
	AFFECT_FIRE,
	AFFECT_CAST_SPEED,
	AFFECT_HP_RECOVER_CONTINUE,
	AFFECT_SP_RECOVER_CONTINUE,

	AFFECT_POLYMORPH,		// 220
	AFFECT_MOUNT,

	AFFECT_WAR_FLAG,		// 222

	AFFECT_BLOCK_CHAT,		// 223
	AFFECT_CHINA_FIREWORK,

	AFFECT_BOW_DISTANCE,	// 225
	AFFECT_DEF_GRADE,		// 226
	AFFECT_SLOW_SHOOT, // 227
	AFFECT_BLOODTHIRST, //228

	AFFECT_DEBUFF_HEAVEN_PROTECTION, // 229

	AFFECT_HEAL_ON_DAMAGE,
	AFFECT_REMOVE_ALL_RESIST,
	AFFECT_SPY,

	AFFECT_HEAVEN_PROTECTION,

	AFFECT_ROOT,

	AFFECT_HORSE_PENALTY = 300,

	AFFECT_NOG_ABILITY = 302,
	AFFECT_HOLLY_STONE_POWER = 303,

	AFFECT_SPRINT = 304,
	AFFECT_QUEST_USE,
	AFFECT_TEMPLE_CURSE,

	AFFECT_COLLECT_NO_TIME,
	AFFECT_COLLECT_NO_FAIL_TIME,
	AFFECT_LEARN_NO_FAIL_TIME,
	AFFECT_EXP_BLOCK,
	AFFECT_HERBALIST_BONUS,

	AFFECT_POTION_START = 350,
	AFFECT_POTION_GENERAL_USE = AFFECT_POTION_START,
	AFFECT_POTION_BOOST,
	AFFECT_POTION_OFFENSIVE,
	AFFECT_POTION_DEFENSIVE,
	AFFECT_POTION_FOOD,
	AFFECT_POTION_END,

	AFFECT_MONKEY_CURSE_EASY = 361,
	AFFECT_MONKEY_CURSE_NORMAL = 362,
	AFFECT_MONKEY_CURSE_HARD = 363,

	AFFECT_DEVILTOWER_DAMAGE = 365,

	AFFECT_FAST_PICKUP,

	AFFECT_NO_ITEM_DEATH_PENALTY,

	AFFECT_PREMIUM_START = 500,
	AFFECT_EXP_BONUS = 500,
	AFFECT_ITEM_BONUS = 501,
	AFFECT_SAFEBOX = 502,
	AFFECT_AUTOLOOT = 503,
	AFFECT_FISH_MIND = 504,
	AFFECT_MARRIAGE_FAST = 505,
	AFFECT_GOLD_BONUS = 506,
	AFFECT_SHOP_PREMIUM = 507,
	AFFECT_PREMIUM_END = 509,

	AFFECT_MALL = 510,
	AFFECT_NO_DEATH_PENALTY = 511,
	AFFECT_SKILL_BOOK_BONUS = 512,
	AFFECT_SKILL_NO_BOOK_DELAY = 513,

	AFFECT_HAIR = 514,
	AFFECT_COLLECT = 515,
	AFFECT_EXP_BONUS_EURO_FREE = 516,
	AFFECT_EXP_BONUS_EURO_FREE_UNDER_15 = 517,
	AFFECT_UNIQUE_ABILITY = 518,

	AFFECT_CUBE_1,
	AFFECT_CUBE_2,
	AFFECT_CUBE_3,
	AFFECT_CUBE_4,
	AFFECT_CUBE_5,
	AFFECT_CUBE_6,
	AFFECT_CUBE_7,
	AFFECT_CUBE_8,
	AFFECT_CUBE_9,
	AFFECT_CUBE_10,
	AFFECT_CUBE_11,
	AFFECT_CUBE_12,

	AFFECT_BLEND,


	AFFECT_HORSE_NAME,
	AFFECT_MOUNT_BONUS,

	AFFECT_AUTO_HP_RECOVERY = 534,
	AFFECT_AUTO_SP_RECOVERY = 535,

	AFFECT_DRAGON_SOUL_QUALIFIED = 540,
	AFFECT_DRAGON_SOUL_DECK_0 = 541,
	AFFECT_DRAGON_SOUL_DECK_1 = 542,

	AFFECT_PREMIUM_SUBSCRIPTION = 543,
	AFFECT_DS_SET = 544,
	AFFECT_QUEST_START_IDX = 1000
};

enum EAffectBits
{
#ifdef __INC_SERVICE_H__
	AFF_NONE,
#endif

	AFF_YMIR,
	AFF_INVISIBILITY,
	AFF_SPAWN,

	AFF_POISON,
	AFF_SLOW,
	AFF_STUN,

	AFF_DUNGEON_READY,
	AFF_DUNGEON_UNIQUE,
	AFF_SHOW_ALWAYS = AFF_DUNGEON_UNIQUE,

	AFF_BUILDING_CONSTRUCTION_SMALL,
	AFF_BUILDING_CONSTRUCTION_LARGE,
	AFF_BUILDING_UPGRADE,

	AFF_MOV_SPEED_POTION,
	AFF_ATT_SPEED_POTION,

	AFF_FISH_MIND,

	AFF_SKILL_BERSERK,			//	AFF_JEONGWIHON
	AFF_SKILL_SWORD_AURA,		//	AFF_GEOMGYEONG
	AFF_SKILL_STRONG_BODY,		//	AFF_CHEONGEUN
	AFF_SKILL_FEATHER_WALK,		//	AFF_GYEONGGONG
	AFF_SKILL_STEALTH,			//	AFF_EUNHYUNG
	AFF_SKILL_ENCHANTED_BLADE,	//	AFF_GWIGUM
	AFF_SKILL_TERROR,			//	AFF_TERROR
	AFF_SKILL_ENCHANTED_ARMOR,	//	AFF_JUMAGAP
	AFF_SKILL_BLESSING,			//	AFF_HOSIN
	AFF_SKILL_REFLECT,			//	AFF_BOHO
	AFF_SKILL_SWIFTNESS,		//	AFF_KWAESOK
	AFF_SKILL_MANASHIELD,		//	AFF_MANASHIELD
	AFF_SKILL_FLAME_SPIRIT,		//	AFF_MUYEONG
	AFF_REVIVE_INVISIBLE,
	AFF_FIRE,
	AFF_SKILL_DRAGON_HELP,		//	AFF_GICHEON
	AFF_SKILL_ATTACK_UP,		//	AFF_JEUNGRYEOK
	AFF_CHARGE_DASH,			//	AFF_TANHWAN_DASH
	AFF_SKILL_DISPEL,			//	AFF_PABEOP
	AFF_SKILL_STRONG_BODY_WITH_FALL, //	AFF_CHEONGEUN_WITH_FALL
	AFF_POLYMORPH,
	AFF_WAR_FLAG1,
	AFF_WAR_FLAG2,
	AFF_WAR_FLAG3,


	AFF_CHINA_FIREWORK,
	AFF_HAIR,
	AFF_SPRINT,
	AFF_SPRINT_HORSE, //client only
	AFF_BLOODTHIRST,
	AFF_HEAVEN_PROTECTION,
	AFF_FIRE_RAGE,
	AFF_DEMONIC_SPIRIT,
	AFF_QUEST_BOX,
	AFF_ROOT,


#ifdef ENABLE_WOLFMAN_CHARACTER
	AFF_BLEEDING,
	AFF_RED_POSSESSION,
	AFF_BLUE_POSSESSION,
#endif

	AFF_BITS_MAX
};

enum
{
	FLY_NONE,
	FLY_EXP,
	FLY_HP_MEDIUM,
	FLY_HP_BIG,
	FLY_SP_SMALL,
	FLY_SP_MEDIUM,
	FLY_SP_BIG,
	FLY_FIREWORK1,
	FLY_FIREWORK2,
	FLY_FIREWORK3,
	FLY_FIREWORK4,
	FLY_FIREWORK5,
	FLY_FIREWORK6,
	FLY_FIREWORK_CHRISTMAS,
	FLY_CHAIN_LIGHTNING,
	FLY_HP_SMALL,
	FLY_SKILL_FLAME_SPIRIT,
#ifdef ENABLE_QUIVER_SYSTEM
	FLY_QUIVER_ATTACK_NORMAL,
#endif
};
enum EPointTypes
{
	POINT_NONE,	// 0
	POINT_LEVEL, 	// 1
	POINT_VOICE,	// 2
	POINT_EXP,	// 3
	POINT_NEXT_EXP,	// 4
	POINT_HP,	// 5
	POINT_MAX_HP,	// 6
	POINT_SP,	// 7
	POINT_MAX_SP,	// 8
	POINT_STAMINA,	// 9
	POINT_MAX_STAMINA,	// 10
	POINT_GOLD,	// 11
	POINT_ST,	// 12
	POINT_HT,	// 13
	POINT_DX,	// 14
	POINT_IQ,	// 15
	POINT_DEF_GRADE,	// 16
	POINT_ATT_SPEED,	// 17
	POINT_ATT_GRADE,	// 18
	POINT_MOV_SPEED,	// 19
	POINT_CLIENT_DEF_GRADE,	// 20
	POINT_CASTING_SPEED,	// 21
	POINT_MAGIC_ATT_GRADE,	// 22
	POINT_MAGIC_DEF_GRADE,	// 23
	POINT_EMPIRE_POINT,	// 24
	POINT_LEVEL_STEP,	// 25
	POINT_STAT,	// 26
	POINT_SUB_SKILL,	// 27
	POINT_SKILL,	// 28
	POINT_WEAPON_MIN,	// 29
	POINT_WEAPON_MAX,	// 30
	POINT_PLAYTIME,	// 31
	POINT_HP_REGEN,	// 32
	POINT_SP_REGEN,	// 33
	POINT_BOW_DISTANCE, 	// 34
	POINT_HP_RECOVERY,	// 35
	POINT_SP_RECOVERY,	// 36
	POINT_POISON_PCT,	// 37
	POINT_STUN_PCT,	// 38
	POINT_SLOW_PCT,	// 39
	POINT_CRITICAL_PCT,	// 40
	POINT_PENETRATE_PCT,	// 41
	POINT_CURSE_PCT,	// 42
	POINT_ATTBONUS_HUMAN,	// 43
	POINT_ATTBONUS_ANIMAL,	// 44
	POINT_ATTBONUS_ORC,	// 45
	POINT_ATTBONUS_MILGYO,	// 46
	POINT_ATTBONUS_UNDEAD,	// 47
	POINT_ATTBONUS_DEVIL,	// 48
	POINT_ATTBONUS_INSECT,	// 49
	POINT_ATTBONUS_FIRE,	// 50
	POINT_ATTBONUS_ICE,	// 51
	POINT_ATTBONUS_DESERT, 	// 52
	POINT_ATTBONUS_MONSTER,	// 53
	POINT_ATTBONUS_WARRIOR,	// 54
	POINT_ATTBONUS_ASSASSIN,	// 55
	POINT_ATTBONUS_SURA,	// 56
	POINT_ATTBONUS_SHAMAN,	// 57
	POINT_ATTBONUS_TREE,     	// 58
	POINT_RESIST_WARRIOR,	// 59
	POINT_RESIST_ASSASSIN,	// 60
	POINT_RESIST_SURA,	// 61
	POINT_RESIST_SHAMAN,	// 62
	POINT_STEAL_HP,	// 63
	POINT_STEAL_SP,	// 64
	POINT_MANA_BURN_PCT,	// 65
	POINT_DAMAGE_SP_RECOVER,	// 66
	POINT_BLOCK,	// 67
	POINT_DODGE,	// 68
	POINT_RESIST_SWORD,	// 69
	POINT_RESIST_TWOHAND,	// 70
	POINT_RESIST_DAGGER,	// 71
	POINT_RESIST_BELL,	// 72
	POINT_RESIST_FAN,	// 73
	POINT_RESIST_BOW,	// 74
	POINT_RESIST_FIRE,	// 75
	POINT_RESIST_ELEC,	// 76
	POINT_RESIST_MAGIC,	// 77
	POINT_RESIST_WIND,	// 78
	POINT_REFLECT_MELEE,	// 79
	POINT_REFLECT_ARROW,	// 80
	POINT_POISON_REDUCE,	// 81
	POINT_KILL_SP_RECOVER,	// 82
	POINT_EXP_DOUBLE_BONUS,	// 83
	POINT_GOLD_DOUBLE_BONUS,	// 84
	POINT_ITEM_DROP_BONUS,	// 85
	POINT_POTION_BONUS,	// 86
	POINT_KILL_HP_RECOVERY,	// 87
	POINT_IMMUNE_STUN,	// 88
	POINT_IMMUNE_SLOW,	// 89
	POINT_IMMUNE_FALL,	// 90
	POINT_PARTY_ATTACKER_BONUS,	// 91
	POINT_PARTY_TANKER_BONUS,	// 92
	POINT_ATT_BONUS,	// 93
	POINT_DEF_BONUS,	// 94
	POINT_ATT_GRADE_BONUS,	// 95
	POINT_DEF_GRADE_BONUS,	// 96
	POINT_MAGIC_ATT_GRADE_BONUS,	// 97
	POINT_MAGIC_DEF_GRADE_BONUS,	// 98
	POINT_RESIST_NORMAL_DAMAGE,	// 99
	POINT_HIT_HP_RECOVERY,	// 100
	POINT_HIT_SP_RECOVERY, 	// 101
	POINT_MANASHIELD,	// 102
	POINT_PARTY_BUFFER_BONUS,	// 103
	POINT_PARTY_SKILL_MASTER_BONUS,	// 104
	POINT_HP_RECOVER_CONTINUE,	// 105
	POINT_SP_RECOVER_CONTINUE,	// 106
	POINT_STEAL_GOLD,	// 107
	POINT_POLYMORPH,	// 108
	POINT_MOUNT,	// 109
	POINT_PARTY_HASTE_BONUS,	// 110
	POINT_PARTY_DEFENDER_BONUS,	// 111
	POINT_STAT_RESET_COUNT,	// 112
	POINT_HORSE_SKILL,	// 113
	POINT_MALL_ATTBONUS,	// 114
	POINT_MALL_DEFBONUS,	// 115
	POINT_MALL_EXPBONUS,	// 116
	POINT_MALL_ITEMBONUS,	// 117
	POINT_MALL_GOLDBONUS,	// 118
	POINT_MAX_HP_PCT,	// 119
	POINT_MAX_SP_PCT,	// 120
	POINT_SKILL_DAMAGE_BONUS,	// 121
	POINT_NORMAL_HIT_DAMAGE_BONUS,	// 122
	POINT_SKILL_DEFEND_BONUS,	// 123
	POINT_NORMAL_HIT_DEFEND_BONUS,	// 124
	POINT_PC_BANG_EXP_BONUS,	// 125
	POINT_PC_BANG_DROP_BONUS,	// 126
	POINT_RAMADAN_CANDY_BONUS_EXP,	// 127
	POINT_ENERGY = 128,	// 128
	POINT_ENERGY_END_TIME = 129,	// 129
	POINT_COSTUME_ATTR_BONUS = 130,	// 130
	POINT_MAGIC_ATT_BONUS_PER = 131,	// 131
	POINT_MELEE_MAGIC_ATT_BONUS_PER = 132,	// 132
	POINT_RESIST_ICE = 133,	// 133
	POINT_RESIST_EARTH = 134,	// 134
	POINT_RESIST_DARK = 135, 	// 135
	POINT_RESIST_CRITICAL = 136,	// 136
	POINT_RESIST_PENETRATE = 137,	// 137
	POINT_TERROR, // 138
	POINT_ST_REGEN, // 139
	POINT_DAGGER_ATT_GRADE_MONSTER, // 140
	POINT_ATT_GRADE_MONSTER, // 141
	POINT_RESIST_MONSTER_1000PCT, // 142
	POINT_ABSORB_DAMAGE, // 143
	POINT_ABSORB_DAMAGE_MONSTER, // 144
	POINT_IMMUNE_STUN_BREAK, // 145
	POINT_BREAK_TEMPLE_CURSE, // 146

	POINT_SKILL_DURATION,
	POINT_ATTBONUS_ORC_VALLEY,
	POINT_ATTBONUS_STONE,
	POINT_ATTBONUS_BOSS,
	POINT_MAGIC_ATT_MONSTER,
	POINT_BREAK_RESIST_SWORD,
	POINT_BREAK_RESIST_TWOHAND,
	POINT_BREAK_RESIST_DAGGER,
	POINT_BREAK_RESIST_BELL,
	POINT_BREAK_RESIST_FAN,
	POINT_BREAK_RESIST_BOW,

	POINT_COLLECT_CHANCE,
	POINT_LEARN_CHANCE,
	POINT_RESIST_HUMAN,

	POINT_MAGIC_ATT,
	POINT_FIRE_PCT,
	POINT_CONVERT_DAMAGE_TO_SP,
	POINT_DROP_RARE,

	POINT_MAGIC_ATT_GRADE_BONUS_MONSTER,
	POINT_ROOT_PCT,
	POINT_ATT_SPECIAL,
	POINT_DEATH_PENALTY,

	// CLIENT_ONLY
	POINT_MIN_WEP,
	POINT_MAX_WEP,
	POINT_MIN_MAGIC_WEP,
	POINT_MAX_MAGIC_WEP,
	POINT_MIN_ATK,
	POINT_MAX_ATK,
	POINT_HIT_RATE,
	POINT_EVADE_RATE,	// 145
	// END OF CLIENT_ONLY

#ifdef ENABLE_ACCE_COSTUME_SYSTEM
	// Metadata carried by sash item_proto. Keep it at the end so enabling
	// the sash system does not renumber any existing gameplay point.
	POINT_ACCEDRAIN_RATE,
#endif

	POINT_MAX_NUM,
};

enum EDragonSoulRefineWindowSize
{
	DRAGON_SOUL_REFINE_GRID_MAX = 15,
};

enum EMisc2
{
	DRAGON_SOUL_EQUIP_SLOT_START = INVENTORY_MAX_NUM + WEAR_MAX_NUM,
	DRAGON_SOUL_EQUIP_SLOT_END = DRAGON_SOUL_EQUIP_SLOT_START + (DS_SLOT_MAX * DRAGON_SOUL_DECK_MAX_NUM),
	DRAGON_SOUL_EQUIP_RESERVED_SLOT_END = DRAGON_SOUL_EQUIP_SLOT_END + (DS_SLOT_MAX * DRAGON_SOUL_DECK_RESERVED_MAX_NUM),

	BELT_INVENTORY_SLOT_START = DRAGON_SOUL_EQUIP_RESERVED_SLOT_END,
	BELT_INVENTORY_SLOT_END = BELT_INVENTORY_SLOT_START + BELT_INVENTORY_SLOT_COUNT,

	INVENTORY_AND_EQUIP_SLOT_MAX = BELT_INVENTORY_SLOT_END,
};

enum EFishingGameEvents
{
	FISHING_GAME_EVENT_NONE,
	FISHING_GAME_EVENT_STOP,
	FISHING_GAME_EVENT_REVERSE,
	FISHING_GAME_EVENT_SPEEDUP,
};

enum ESpecialShop
{
	SPECIAL_SHOP_MAX_LIMIT = 2,
	SPECIAL_SHOP_MAX_ITEM_COUNT = 4,
};

enum ESpecialShopPriceType {
	SPECIAL_SHOP_PRICE_GOLD,
	SPECIAL_SHOP_PRICE_REPUTATION,
};

enum ESpecialShopLimitTypes {
	SPECIAL_SHOP_LIMIT_NONE,
	SPECIAL_SHOP_LIMIT_LEVEL,
	SPECIAL_SHOP_LIMIT_REPUTATION,
	SPECIAL_SHOP_LIMIT_BUY_PER_TIME,
	SPECIAL_SHOP_LIMIT_ACCOUNT,
};

#pragma pack(push, 1)

typedef struct SItemPos
{
	BYTE window_type;
	WORD cell;
    SItemPos ()
    {
        window_type = INVENTORY;
		cell = WORD_MAX;
    }

	SItemPos (BYTE _window_type, WORD _cell)
    {
        window_type = _window_type;
        cell = _cell;
    }

	bool IsValidItemPosition() const
	{
		switch (window_type)
		{
		case RESERVED_WINDOW:
			return false;
		case INVENTORY:
		case EQUIPMENT:
		case BELT_INVENTORY:
			return cell < INVENTORY_AND_EQUIP_SLOT_MAX;
		case DRAGON_SOUL_INVENTORY:
			return cell < (DRAGON_SOUL_INVENTORY_MAX_NUM);

		case SAFEBOX:
		case MALL:
			return false;
		default:
			return false;
		}
		return false;
	}

	bool IsSamePosition(const SItemPos & other) const
	{
		return *this==other
			|| ((INVENTORY == window_type || EQUIPMENT == window_type)
				&& (INVENTORY == other.window_type || EQUIPMENT == other.window_type)
				&& cell == other.cell);
	}

	bool IsEquipPosition() const
	{
		return ((INVENTORY == window_type || EQUIPMENT == window_type) && cell >= INVENTORY_MAX_NUM && cell < INVENTORY_MAX_NUM + WEAR_MAX_NUM)
			|| IsDragonSoulEquipPosition();
	}

	bool IsDragonSoulEquipPosition() const
	{
		return (window_type == INVENTORY) && (DRAGON_SOUL_EQUIP_SLOT_START <= cell) && (DRAGON_SOUL_EQUIP_SLOT_END > cell); // @fixme184
	}

	bool IsBeltInventoryPosition() const // @fixme324 (INVENTORY n EQUIPMENT)
	{
		return (window_type == INVENTORY || window_type == EQUIPMENT) && (BELT_INVENTORY_SLOT_START <= cell) && (BELT_INVENTORY_SLOT_END > cell);
	}

	bool IsDefaultInventoryPosition() const
	{
		return INVENTORY == window_type && cell < INVENTORY_MAX_NUM;
	}

	bool operator==(const struct SItemPos& rhs) const
	{
		return (window_type == rhs.window_type) && (cell == rhs.cell);
	}
	bool operator<(const struct SItemPos& rhs) const
	{
		return (window_type < rhs.window_type) || ((window_type == rhs.window_type) && (cell < rhs.cell));
	}
} TItemPos;

const TItemPos NPOS (RESERVED_WINDOW, WORD_MAX);

typedef struct SItemPosEx
{
	TItemPos pos;
	int id{ 0 };
} TItemPosEx;

typedef enum
{
	SHOP_COIN_TYPE_GOLD, // DEFAULT VALUE
	SHOP_COIN_TYPE_SECONDARY_COIN,
} EShopCoinType;

enum EFractions
{
	FRACTION_NONE,
	FRACTION_DESERT,
	FRACTION_ORC_VALLEY,
	FRACTION_MAX_NUM,

	REPUTATION_MAX_TOTAL_VALUE = 38500,
};

enum ESpecialFlags
{

	SHOP_SLOT_UNLOCK_PROGRESS_FLAG,
	HORSE_INVENTORY_UNLOCK_PROGRES_FLAG,

	PLAYER_STATS_FLAG_START = 10,
	PLAYER_STATS_MONSTER_FLAG,
	PLAYER_STATS_BOSS_FLAG,
	PLAYER_STATS_MINIBOSS_FLAG,
	PLAYER_STATS_STONE_FLAG,
	PLAYER_STATS_DUNGEON_FLAG,
	PLAYER_STATS_EMPIRE_FLAG,
	PLAYER_STATS_DUEL_FLAG,
	PLAYER_STATS_MINING_FLAG,
	PLAYER_STATS_FISHING_FLAG,
	PLAYER_STATS_HERBALISM_FLAG,
	PLAYER_STATS_CHEST_FLAG,
	PLAYER_STATS_QUESTBOOK_FLAG,
	PLAYER_STATS_DEATH_FLAG,
	PLAYER_STATS_DEATH_FROM_MOB_FLAG,
	PLAYER_STATS_DEATH_FROM_PLAYER_FLAG,
	PLAYER_STATS_DAMAGE_FLAG,
	PLAYER_STATS_DAMAGE_HORSE_FLAG,
	PLAYER_STATS_DAMAGE_SKILL_FLAG,
	PLAYER_STATS_GOLD_FLAG,
	PLAYER_STATS_GOLD_SELL_SHOP_FLAG,
	PLAYER_STATS_REFINE_SUCCESS_FLAG,
	PLAYER_STATS_REFINE_FAIL_SMITH_FLAG,
	PLAYER_STATS_FLAG_END,
	PLAYER_STATS_FLAG_MAX = 50,

	REPUTATION_FLAG_START = 100,
	REPUTATION_DESERT = REPUTATION_FLAG_START + FRACTION_DESERT,
	REPUTATION_ORC_VALLEY = REPUTATION_FLAG_START + FRACTION_ORC_VALLEY,
	REPUTATION_FLAG_END = REPUTATION_FLAG_START + FRACTION_MAX_NUM,

	SPECIAL_FLAG_MAX_LEN = 32,
};

enum EHitTypes
{
	HIT_TYPE_NONE,
	HIT_TYPE_GREAT,
	HIT_TYPE_GOOD,
};

enum ECustomNpcFlags
{
	CUSTOM_NPC_FLAG_PURGE_ON_AGGRO_LOSE = (1 << 0),
	CUSTOM_NPC_FLAG_LOCK_INTERACTION = (1 << 1),
	CUSTOM_NPC_FLAG_SEE_OTHER = (1 << 2),
};

enum ETime {
	SECONDS_IN_MINUTE = 60,
	SECONDS_IN_HOUR = SECONDS_IN_MINUTE * 60,
	SECONDS_IN_DAY = SECONDS_IN_HOUR * 24,
};

enum EBusyActionTypes
{
	BUSY_ACTION_GENERAL,
	BUSY_ACTION_HERB,
};

enum EBusyAction
{
	BUSY_EXCHANGE = (1 << 0),
	BUSY_SAFEBOX = (1 << 1),
	BUSY_CUBE = (1 << 2),
	BUSY_SHOP_MANAGE = (1 << 3),
	BUSY_MYSHOP = (1 << 4),
	BUSY_SHOP = (1 << 5),
	BUSY_ITEMSHOP = (1 << 6),
	BUSY_CRAFTING = (1 << 7),
	BUSY_WARP = (1 << 8),
	BUSY_SPECIAL_SHOP = (1 << 9),
	BUSY_POTION_RECHARGE = (1 << 10),
	BUSY_ITEM_EXCHANGE = (1 << 11),

	BUSY_CAN_HANDLE_ITEM_EXCLUDE = BUSY_ITEMSHOP,
};

enum EPlayerDeleteErrorType
{
	PLAYER_DELETE_GENERAL_ERROR,
	PLAYER_DELETE_WRONG_SOCIAL_ID,
	PLAYER_DELETE_ABOVE_LEVEL_LIMIT,
	PLAYER_DELETE_USING_OFFLINESHOP,

};

enum ECaptcha
{
	// feedback
	CAPTCHA_OK,
	CAPTCHA_NO_ATTEMPTS,
	CAPTCHA_WRONG_CODE,
	CAPTCHA_EXPIRE,
	CAPTCHA_REQUEST_CHANGE,
	CAPTCHA_DISCONNECT,

	CAPTCHA_DURATION = 90,
	CAPTCHA_MAX_ATTEMPTS = 4,
	CAPTCHA_MAX_LEN = 8,
	CAPTCHA_MAX_CHANGE_REQUESTS = 2,
	CAPTCHA_CODE_DEFAULT_LEN = 6,
};

enum EMessenger {
	MESSENGER_MAX_FRIEND_LIMIT = 100,
	MESSENGER_MAX_BLOCK_LIMIT = 100,
};

enum EShopOfflineSearchCategories {
	SHOP_SEARCH_CATEGORY_BOOKS,
	SHOP_SEARCH_CATEGORY_REFINE,
	SHOP_SEARCH_CATEGORY_SOULSTONE,
	SHOP_SEARCH_CATEGORY_HERBALISM,
	SHOP_SEARCH_CATEGORY_FISHING,
	SHOP_SEARCH_CATEGORY_HORSE,
	SHOP_SEARCH_CATEGORY_SPECIAL,
	SHOP_SEARCH_CATEGORY_MINING,
	SHOP_SEARCH_CATEGORY_POLYMORPH,
	SHOP_SEARCH_CATEGORY_ARMOR,
	SHOP_SEARCH_CATEGORY_ARMOR_ATTR,
	SHOP_SEARCH_CATEGORY_WEAPON,
	SHOP_SEARCH_CATEGORY_WEAPON_ATTR,
	SHOP_SEARCH_CATEGORY_JEWELRY,
	SHOP_SEARCH_CATEGORY_JEWELRY_ATTR,
	SHOP_SEARCH_CATEGORY_MAX,

	SHOP_SEARCH_SUB_WARRIOR_0 = 0,
	SHOP_SEARCH_SUB_WARRIOR_1,
	SHOP_SEARCH_SUB_ASSASSIN_0,
	SHOP_SEARCH_SUB_ASSASSIN_1,
	SHOP_SEARCH_SUB_SURA_0,
	SHOP_SEARCH_SUB_SURA_1,
	SHOP_SEARCH_SUB_SHAMAN_0,
	SHOP_SEARCH_SUB_SHAMAN_1,
	SHOP_SEARCH_SUB_PASSIVE_SKILL,

	SHOP_SEARCH_SUB_REFINE_M1 = 0,
	SHOP_SEARCH_SUB_REFINE_OATH,
	SHOP_SEARCH_SUB_REFINE_M2,
	SHOP_SEARCH_SUB_REFINE_ORC,
	SHOP_SEARCH_SUB_REFINE_DESERT1,
	SHOP_SEARCH_SUB_REFINE_DESERT2,
	SHOP_SEARCH_SUB_REFINE_SNOW,
	SHOP_SEARCH_SUB_REFINE_HWANG,
	SHOP_SEARCH_SUB_REFINE_END,
	SHOP_SEARCH_SUB_REFINE_SPECIAL,
	SHOP_SEARCH_SUB_REFINE_PEARL,

	SHOP_SEARCH_SUB_SOULSTONE_0 = 0,
	SHOP_SEARCH_SUB_SOULSTONE_1,
	SHOP_SEARCH_SUB_SOULSTONE_2,
	SHOP_SEARCH_SUB_SOULSTONE_3,
	SHOP_SEARCH_SUB_SOULSTONE_4,


	SHOP_SEARCH_SUB_HERB_PRIMARY = 0,
	SHOP_SEARCH_SUB_HERB_SPECIAL,
	SHOP_SEARCH_SUB_HERB_WATER_OFFENSIVE,
	SHOP_SEARCH_SUB_HERB_WATER_DEFENSIVE,
	SHOP_SEARCH_SUB_HERB_WATER_POWER,
	SHOP_SEARCH_SUB_HERB_JUICE_OFFENSIVE,
	SHOP_SEARCH_SUB_HERB_JUICE_DEFENSIVE,
	SHOP_SEARCH_SUB_HERB_JUICE_POWER,
	SHOP_SEARCH_SUB_HERB_DEW_OFFENSIVE,
	SHOP_SEARCH_SUB_HERB_DEW_DEFENSIVE,
	SHOP_SEARCH_SUB_HERB_DEW_POWER,
	SHOP_SEARCH_SUB_HERB_OTHER_POTION,
	SHOP_SEARCH_SUB_HERB_AUTOPOTION,
	SHOP_SEARCH_SUB_HERB_RECIPE_OFFENSIVE,
	SHOP_SEARCH_SUB_HERB_RECIPE_DEFENSIVE,
	SHOP_SEARCH_SUB_HERB_RECIPE_POWER,
	SHOP_SEARCH_SUB_HERB_RECIPE_OTHER,

	SHOP_SEARCH_SUB_FISHING_FISH = 0,
	SHOP_SEARCH_SUB_FISHING_FISH_COOK,
	SHOP_SEARCH_SUB_FISHING_FISH_OTHER,

	SHOP_SEARCH_SUB_SPECIAL_REFINE = 0,
	SHOP_SEARCH_SUB_SPECIAL_TOITEM,
	SHOP_SEARCH_SUB_SPECIAL_CHARACTER,
	SHOP_SEARCH_SUB_SPECIAL_OTHER,
	SHOP_SEARCH_SUB_SPECIAL_DRAGON_VOUCHER,
	SHOP_SEARCH_SUB_SPECIAL_QUEST,
	SHOP_SEARCH_SUB_SPECIAL_LOOTBOX,

	SHOP_SEARCH_SUB_MINING_ORE = 0,
	SHOP_SEARCH_SUB_MINING_MELT,

	SHOP_SEARCH_SUB_ARMOR_BODY = 0,
	SHOP_SEARCH_SUB_ARMOR_SHIELD,
	SHOP_SEARCH_SUB_ARMOR_HEAD,

	SHOP_SEARCH_SUB_WEAPON_ONEHAND = 0,
	SHOP_SEARCH_SUB_WEAPON_TWOHAND,
	SHOP_SEARCH_SUB_WEAPON_DAGGER,
	SHOP_SEARCH_SUB_WEAPON_BOW,
	SHOP_SEARCH_SUB_WEAPON_BELL,
	SHOP_SEARCH_SUB_WEAPON_FAN,

	SHOP_SEARCH_SUB_JEWELRY_EAR = 0,
	SHOP_SEARCH_SUB_JEWELRY_NECK,
	SHOP_SEARCH_SUB_JEWELRY_WRIST,
	SHOP_SEARCH_SUB_JEWELRY_BOOTS,

	SHOP_SEARCH_SUB_HORSE_LEARN = 0,
	SHOP_SEARCH_SUB_HORSE_OTHER,

	SHOP_CATEGORY_MAX_SUB = 20,
};

enum EUseCodeVoucherResponse
{
	USE_VOUCHER_SUCCESS,
	USE_VOUCHER_NO_CODE,
	USE_VOUCHER_ALREADY_USED,
	USE_VOUCHER_TRY_AGAIN_LATER,
};

#pragma pack(pop)

#endif
//martysama0134's 4e4e75d8b719b9240e033009cf4d7b0f

// Files shared by GameCore.top
