# -*- coding: utf-8 -*-
# MT2009_PLUS_AREZZO_COSTUME_SETS_V1 - the server side of the Arezzo costume sets, written from
# azcostume_items.json (the same rows patch_azcostume_client.py puts into the client):
#
#   python3 gen_azcostume_server.py <repo>
#
#   linux-port/docker/mariadb/playerbot/arezzo_costumes.sql      world.item_proto, INSERT IGNORE
#   linux-port/docker/mariadb/playerbot/arezzo_costumes_webshop.sql  the web ItemShop's offers
#   linux-port/docker/mariadb/playerbot/apply.sh                 the in-game ItemShop lines (the
#                                                                ishop_once block between the markers)
#   linux-port/docker/game/costume_sets.txt                      the sets (bonus: body + hair of a set)
#   client-patches/client-2.0.30/root/costume_sets.py            the tooltip's copy of the sets
#   linux-port/docker/itemshop/app/itemshop/img/item/<vnum>.png  the web shop's icons (from the
#                                                                client icons, TGA / PNG -> PNG)
# Idempotent: a second run writes the same files.
import json
import os
import struct
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import azcostume_sets as A  # noqa: E402

MARK = 'MT2009_PLUS_AREZZO_COSTUME_SETS_V1'
ISHOP_BASE = {'HairData': 10600, 'ShapeData': 20600, 'Weapon': 30600, 'SashSkin': 30800}
WEB_CATEGORY = {'HairData': 5, 'ShapeData': 6, 'Weapon': 7, 'SashSkin': 7}
CLASS_WEB = {0: u'Wojownik, Ninja, Sura', 1: u'Ninja', 2: u'Ninja', 3: u'Wojownik', 4: u'Szaman', 5: u'Szaman'}
COLS = ('vnum, name, locale_name, type, subtype, stack, weight, size, antiflag, flag, wearflag, immuneflag, gold, '
        'shop_buy_price, refined_vnum, refine_set, magic_pct, specular, socket_pct, addon_type, limittype0, '
        'limitvalue0, limittype1, limitvalue1, applytype0, applyvalue0, applytype1, applyvalue1, applytype2, '
        'applyvalue2, value0, value1, value2, value3, value4, value5, socket0, socket1, socket2, socket3, socket4, '
        'socket5')
ICON_SRC = '/opt/metin2/cache/arezzo/cpack/files'


def load():
    with open(os.path.join(HERE, 'azcostume_items.json'), encoding='utf-8') as f:
        return json.load(f)


def q(s):
    return u"'%s'" % s.replace(u"\\", u"\\\\").replace(u"'", u"''")


def proto_row(it):
    skin = it['kind'] == 'SashSkin'
    flag = 1 << 14 if skin else 0                      # ITEM_FLAG_APPLICABLE: "use on item"
    limit = (0, 0) if skin else A.LIMIT_DAYS30
    magic, spec = (0, 0) if skin else (A.MAGIC_PCT, A.SPECULAR)
    v = it['values']
    return (u'(%d, %s, %s, %d, %d, 1, 0, %d, %d, %d, 0, \'\', 0, 0, 0, 0, %d, %d, 0, 0, %d, %d, 0, 0, '
            u'0, 0, 0, 0, 0, 0, %d, %d, %d, %d, %d, %d, -1, -1, -1, -1, -1, -1)') % (
        it['vnum'], q(it['name']), q(it['name']), it['type'], it['sub'], it['size'], it['anti'], flag,
        magic, spec, limit[0], limit[1], v[0], v[1], v[2], v[3], v[4], v[5])


def sql_items(items):
    head = (u'-- %s (generated by client-patches/client-2.0.30/tools/azcostume/gen_azcostume_server.py from\n'
            u'-- azcostume_items.json - do not edit by hand): the Arezzo costume sets, %d items. Bodies 42900-42963\n'
            u'-- (Arezzo 419xx + 1000), hairs 45900-45963, weapon skins 40600-40995 (costume 28/4, value3 = the\n'
            u'-- weapon type), sash skins 85200-85221 (use 3/10 + ITEM_FLAG_APPLICABLE, server-patches/azcostume).\n'
            u'-- No built-in bonus (owner: "bez zadnych dodatkowych bonusow"): applies 0; like our ItemShop\n'
            u'-- costumes 30 days from the first use, magic_pct 100 (costume bonuses rolled when made), 70063 /\n'
            u'-- 70064 / the bonus transfer as on every costume; the set bonus is costume_sets.txt. INSERT IGNORE:\n'
            u'-- a row the operator changed is kept. apply.sh runs this file at every start (idempotent).\n'
            u'SET NAMES utf8mb4;\n') % (MARK, len(items))
    return head + u'INSERT IGNORE INTO world.item_proto (%s) VALUES\n%s;\n' % (
        COLS, u',\n'.join(proto_row(it) for it in items))


def web_name(it):
    if it['kind'] in ('ShapeData', 'HairData'):
        sex = u'męski' if it['name'].endswith(u'(m)') else u'żeński'
        return u'%s (%s, 30 dni)' % (it['name'], sex), u'Czas: 30 dni.<br />Tylko dla postaci %s.' % (
            u'męskich' if sex == u'męski' else u'żeńskich')
    if it['kind'] == 'Weapon':
        return u'%s (30 dni)' % it['name'], u'Czas: 30 dni.<br />Klasa: %s.' % CLASS_WEB[it['values'][3]]
    return it['name'], (u'Nakładka na szarfę: przeciągnij ją na szarfę w ekwipunku, szarfa przyjmie ten '
                        u'wygląd (bonusy i pochłanianie bez zmian). Bez limitu czasu.')


def sql_web(items):
    out = [u'-- %s (generated, see arezzo_costumes.sql): the web ItemShop (port 7791) offers of the Arezzo\n'
           u'-- costume sets, 100 SM each like our costumes; id 1000000 + vnum, categories 5 Fryzury +, 6 Kostiumy,\n'
           u'-- 7 Nakladki (weapon and sash skins). Once each (NOT EXISTS), only while the item exists.\n'
           u'SET NAMES utf8mb4;\n' % MARK]
    for it in items:
        name, desc = web_name(it)
        out.append(u'INSERT IGNORE INTO itemshop.ishop_items (id, category, name_item, `desc`, price, currency, vnum, '
                   u'count, socket0, socket1, socket2, vnum_icon, date_added)\nSELECT %d, %d, %s, %s, 100, \'cash\', %d, '
                   u'1, 0, 0, 0, \'%d\', NOW() FROM DUAL WHERE EXISTS (SELECT 1 FROM world.item_proto WHERE vnum = %d) '
                   u'AND NOT EXISTS (SELECT 1 FROM itemshop.ishop_items WHERE vnum = %d);\n' % (
                       1000000 + it['vnum'], WEB_CATEGORY[it['kind']], q(name), q(desc), it['vnum'], it['vnum'],
                       it['vnum'], it['vnum']))
    return u''.join(out)


def ishop_lines(items):
    n = dict((k, 0) for k in ISHOP_BASE)
    rows = []
    for it in items:
        idx = ISHOP_BASE[it['kind']] + n[it['kind']]
        n[it['kind']] += 1
        rows.append(u"(%d, %d, 1, 100, 'DRAGON_COIN', 0)" % (idx, it['vnum']))
    return rows


def apply_block(items):
    rows = ishop_lines(items)
    return (u'# >>> %s (generated by gen_azcostume_server.py - do not edit by hand)\n'
            u'# The Arezzo costume sets (client-patches/client-2.0.30/tools/azcostume): the items, every start\n'
            u'# (INSERT IGNORE - a row the operator changed is kept; arezzo_costumes.sql), the in-game ItemShop\n'
            u'# lines once per install like our costumes (100 SM; hairs 10600+, costumes 20600+, weapon skins\n'
            u'# 30600+, sash skins 30800+ in "Nakladki"), and the web shop offers (arezzo_costumes_webshop.sql).\n'
            u'if [ -s /opt/playerbot/arezzo_costumes.sql ]; then\n'
            u'    db < /opt/playerbot/arezzo_costumes.sql || fail_step "could not add the Arezzo costume sets (arezzo_costumes.sql)" >&2\n'
            u'fi\n'
            u'if [ "$(db -e "SELECT COUNT(*) FROM world.item_proto WHERE vnum IN (%d, %d);" 2>/dev/null || echo x)" = "2" ]; then\n'
            u'ishop_once arezzo_costume_sets "INSERT IGNORE INTO common.itemshop_items (\\`index\\`, vnum, count, price, currency, minLevel) VALUES\n'
            u'%s;" "could not add the Arezzo costume sets to the ItemShop"\n'
            u'fi\n'
            u'if [ -s /opt/playerbot/arezzo_costumes_webshop.sql ]; then\n'
            u'    db < /opt/playerbot/arezzo_costumes_webshop.sql 2>/dev/null || echo "[playerbot-migrate] note: no web ItemShop tables for the Arezzo costume sets" >&2\n'
            u'fi\n'
            u'# <<< %s\n') % (MARK, items[0]['vnum'], items[-1]['vnum'], u',\n'.join(rows), MARK)


def put_block(path, block, anchor):
    text = open(path, encoding='utf-8', newline='').read()
    assert '\r\n' not in text, path
    start, end = u'# >>> %s' % MARK, u'# <<< %s\n' % MARK
    if start in text:
        a = text.index(start)
        b = text.index(end, a) + len(end)
        text = text[:a] + block + text[b:]
    else:
        assert text.count(anchor) == 1, anchor
        text = text.replace(anchor, block + anchor)
    open(path, 'w', encoding='utf-8', newline='').write(text)


def costume_sets_txt(path, sets):
    raw = open(path, encoding='utf-8', newline='').read()
    nl = '\r\n' if '\r\n' in raw else '\n'
    lines = raw.replace('\r\n', '\n').split('\n')
    names = set(s['name'] for s in sets)
    keep = [l for l in lines if l.split('\t')[0] not in names and MARK not in l]
    while keep and keep[-1] == '':
        keep.pop()
    keep.append(u'# %s: the Arezzo costume sets (client-patches/client-2.0.30/tools/azcostume) - a costume (m)/(k)'
                % MARK)
    keep.append(u'# and a helmet (m)/(k) of one set give the same bonus as every set here; weapon / sash skins are looks only (%s).' % MARK)
    for s in sets:
        keep.append(u'%s\t%s\t%s' % (s['name'], ','.join(str(v) for v in s['bodies']), ','.join(str(v) for v in s['hairs'])))
    open(path, 'w', encoding='utf-8', newline='').write(nl.join(keep) + nl)
    return keep


def costume_sets_py(path, txt_lines):
    """SETS = (...) of root/costume_sets.py again from costume_sets.txt (its header and the code after stay)."""
    text = open(path, encoding='latin-1', newline='').read()
    assert '\r\n' not in text, path
    a = text.index('SETS = (\n')
    b = text.index('\n)\n', a) + 3
    rows = []
    for l in txt_lines:
        if not l or l.startswith('#'):
            continue
        name, bodies, hairs = l.split('\t')[:3]
        rows.append('\t((%s,), (%s,)),\t# %s' % (bodies, hairs, name))
    text = text[:a] + 'SETS = (\n' + '\n'.join(rows) + '\n)\n' + text[b:]
    open(path, 'w', encoding='latin-1', newline='').write(text)


# --- icons for the web shop: TGA (types 2/10, 24/32 bit) or PNG -> PNG --------------------------
def tga_rgba(b):
    idlen, cmtype, itype = b[0], b[1], b[2]
    w, h, bpp, desc = struct.unpack_from('<HHBB', b, 12)
    assert cmtype == 0 and itype in (2, 10) and bpp in (24, 32), (cmtype, itype, bpp)
    px = bpp // 8
    pos = 18 + idlen
    data = bytearray()
    need = w * h * px
    if itype == 2:
        data = b[pos:pos + need]
    else:
        while len(data) < need:
            c = b[pos]
            pos += 1
            n = (c & 0x7f) + 1
            if c & 0x80:
                data += b[pos:pos + px] * n
                pos += px
            else:
                data += b[pos:pos + px * n]
                pos += px * n
    rows = []
    for y in range(h):
        sy = y if desc & 0x20 else h - 1 - y
        row = bytearray()
        for x in range(w):
            p = data[(sy * w + x) * px:(sy * w + x + 1) * px]
            row += bytes((p[2], p[1], p[0], p[3] if px == 4 else 255))
        rows.append(bytes(row))
    return w, h, rows


def png_bytes(w, h, rows):
    def chunk(t, d):
        return struct.pack('>I', len(d)) + t + d + struct.pack('>I', zlib.crc32(t + d) & 0xffffffff)
    raw = b''.join(b'\0' + r for r in rows)
    return (b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', w, h, 8, 6, 0, 0, 0)) +
            chunk(b'IDAT', zlib.compress(raw, 9)) + chunk(b'IEND', b''))


def web_icon(icon_key):
    src = os.path.join(ICON_SRC, icon_key)
    b = open(src, 'rb').read()
    if b[:8] == b'\x89PNG\r\n\x1a\n':
        return b
    return png_bytes(*tga_rgba(b))


def main():
    if len(sys.argv) != 2:
        raise SystemExit('usage: gen_azcostume_server.py <repo>')
    repo = sys.argv[1]
    d = load()
    items = d['items']
    pb = os.path.join(repo, 'linux-port/docker/mariadb/playerbot')
    open(os.path.join(pb, 'arezzo_costumes.sql'), 'w', encoding='utf-8').write(sql_items(items))
    open(os.path.join(pb, 'arezzo_costumes_webshop.sql'), 'w', encoding='utf-8').write(sql_web(items))
    put_block(os.path.join(pb, 'apply.sh'), apply_block(items), u'# MT2009_PLUS_COLLECTOR_STORAGE_V1: the collector\'s storage (Magazyn\n')
    txt = costume_sets_txt(os.path.join(repo, 'linux-port/docker/game/costume_sets.txt'), d['sets'])
    costume_sets_py(os.path.join(repo, 'client-patches/client-2.0.30/root/costume_sets.py'), txt)
    img = os.path.join(repo, 'linux-port/docker/itemshop/app/itemshop/img/item')
    made = 0
    if os.path.isdir(ICON_SRC):
        for it in items:
            dst = os.path.join(img, '%d.png' % it['vnum'])
            png = web_icon(it['icon'])
            if not os.path.exists(dst) or open(dst, 'rb').read() != png:
                open(dst, 'wb').write(png)
                made += 1
    print('items %d, ItemShop lines %d, sets %d, web icons written %d' % (len(items), len(ishop_lines(items)),
                                                                         len(d['sets']), made))


if __name__ == '__main__':
    main()
