# -*- coding: utf-8 -*-
# MT2009_PLUS_AREZZO_COSTUME_SETS_V1 - the server side of the Arezzo costume sets, written from
# azcostume_items.json (the same rows patch_azcostume_client.py puts into the client):
#
#   python3 gen_azcostume_server.py <repo>
#
#   linux-port/docker/mariadb/playerbot/arezzo_costumes.sql      world.item_proto, INSERT IGNORE
#   linux-port/docker/mariadb/playerbot/arezzo_costumes_webshop.sql  the web ItemShop's offers
#   linux-port/docker/mariadb/playerbot/apply.sh                 the in-game ItemShop lines (the
#                                                                ishop_once block between the markers)
#   linux-port/docker/game/costume_sets.txt                      the sets (bonus: body + hair of a set)
#   client-patches/client-2.0.30/root/costume_sets.py            the tooltip's copy of the sets
#   linux-port/docker/itemshop/app/itemshop/img/item/<vnum>.png  the web shop's icons (from the
#                                                                client icons, TGA / PNG -> PNG)
#   MT2009_PLUS_AREZZO_COSTUME_SETS_V2/V3/V4: removed items' icons deleted here (V3: both sets back;
#   V4: the four "me_w" sash skins azcostume_sets.REMOVED_ITEMS, cleaned up by the apply.sh block) and the gate on the Arezzo module (flag mt2009_arezzo_closed):
#   linux-port/overlays/playerbot/src/game/src/playerbot_arezzo_costumes.h  the vnums for the engine's
#                                                                ItemShop and the bots' catalogue
#   linux-port/docker/itemshop/app/itemshop/arezzo_costumes.php  the same for the web shop
# Idempotent: a second run writes the same files.
import json
import os
import struct
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import azcostume_sets as A  # noqa: E402

MARK = 'MT2009_PLUS_AREZZO_COSTUME_SETS_V1'
MARK2 = 'MT2009_PLUS_AREZZO_COSTUME_SETS_V2'
MARK3 = 'MT2009_PLUS_AREZZO_COSTUME_SETS_V3'
MARK4 = 'MT2009_PLUS_AREZZO_COSTUME_SETS_V4'
ISHOP_BASE = {'HairData': 10600, 'ShapeData': 20600, 'Weapon': 30600, 'SashSkin': 30800}
WEB_CATEGORY = {'HairData': 5, 'ShapeData': 6, 'Weapon': 7, 'SashSkin': 7}
CLASS_WEB = {0: u'Wojownik, Ninja, Sura', 1: u'Ninja', 2: u'Ninja', 3: u'Wojownik', 4: u'Szaman', 5: u'Szaman'}
COLS = ('vnum, name, locale_name, type, subtype, stack, weight, size, antiflag, flag, wearflag, immuneflag, gold, '
        'shop_buy_price, refined_vnum, refine_set, magic_pct, specular, socket_pct, addon_type, limittype0, '
        'limitvalue0, limittype1, limitvalue1, applytype0, applyvalue0, applytype1, applyvalue1, applytype2, '
        'applyvalue2, value0, value1, value2, value3, value4, value5, socket0, socket1, socket2, socket3, socket4, '
        'socket5')
ICON_SRC = '/opt/metin2/cache/arezzo/cpack/files'


def load():
    with open(os.path.join(HERE, 'azcostume_items.json'), encoding='utf-8') as f:
        return json.load(f)


def q(s):
    return u"'%s'" % s.replace(u"\\", u"\\\\").replace(u"'", u"''")


def proto_row(it):
    skin = it['kind'] == 'SashSkin'
    flag = 1 << 14 if skin else 0                      # ITEM_FLAG_APPLICABLE: "use on item"
    limit = (0, 0) if skin else A.LIMIT_DAYS30
    magic, spec = (0, 0) if skin else (A.MAGIC_PCT, A.SPECULAR)
    v = it['values']
    return (u'(%d, %s, %s, %d, %d, 1, 0, %d, %d, %d, 0, \'\', 0, 0, 0, 0, %d, %d, 0, 0, %d, %d, 0, 0, '
            u'0, 0, 0, 0, 0, 0, %d, %d, %d, %d, %d, %d, -1, -1, -1, -1, -1, -1)') % (
        it['vnum'], q(it['name']), q(it['name']), it['type'], it['sub'], it['size'], it['anti'], flag,
        magic, spec, limit[0], limit[1], v[0], v[1], v[2], v[3], v[4], v[5])


def sql_items(items):
    head = (u'-- %s (generated by client-patches/client-2.0.30/tools/azcostume/gen_azcostume_server.py from\n'
            u'-- azcostume_items.json - do not edit by hand): the Arezzo costume sets, %d items. Bodies 42900-42963\n'
            u'-- (Arezzo 419xx + 1000), hairs 45900-45963, weapon skins 40600-40995 (costume 28/4, value3 = the\n'
            u'-- weapon type), sash skins 85200-85221 (use 3/10 + ITEM_FLAG_APPLICABLE, server-patches/azcostume).\n'
            u'-- No built-in bonus (owner: "bez zadnych dodatkowych bonusow"): applies 0; like our ItemShop\n'
            u'-- costumes 30 days from the first use, magic_pct 100 (costume bonuses rolled when made), 70063 /\n'
            u'-- 70064 / the bonus transfer as on every costume; the set bonus is costume_sets.txt. INSERT IGNORE:\n'
            u'-- a row the operator changed is kept. apply.sh runs this file at every start (idempotent).\n'
            u'SET NAMES utf8mb4;\n') % (MARK, len(items))
    return head + u'INSERT IGNORE INTO world.item_proto (%s) VALUES\n%s;\n' % (
        COLS, u',\n'.join(proto_row(it) for it in items))


def web_name(it):
    if it['kind'] in ('ShapeData', 'HairData'):
        sex = u'męski' if it['name'].endswith(u'(m)') else u'żeński'
        return u'%s (%s, 30 dni)' % (it['name'], sex), u'Czas: 30 dni.<br />Tylko dla postaci %s.' % (
            u'męskich' if sex == u'męski' else u'żeńskich')
    if it['kind'] == 'Weapon':
        return u'%s (30 dni)' % it['name'], u'Czas: 30 dni.<br />Klasa: %s.' % CLASS_WEB[it['values'][3]]
    return it['name'], (u'Nakładka na szarfę: przeciągnij ją na szarfę w ekwipunku, szarfa przyjmie ten '
                        u'wygląd (bonusy i pochłanianie bez zmian). Bez limitu czasu.')


def sql_web(items):
    out = [u'-- %s (generated, see arezzo_costumes.sql): the web ItemShop (port 7791) offers of the Arezzo\n'
           u'-- costume sets, 100 SM each like our costumes; id 1000000 + vnum, categories 5 Fryzury +, 6 Kostiumy,\n'
           u'-- 7 Nakladki (weapon and sash skins). Once each (NOT EXISTS), only while the item exists.\n'
           u'SET NAMES utf8mb4;\n' % MARK]
    for it in items:
        name, desc = web_name(it)
        out.append(u'INSERT IGNORE INTO itemshop.ishop_items (id, category, name_item, `desc`, price, currency, vnum, '
                   u'count, socket0, socket1, socket2, vnum_icon, date_added)\nSELECT %d, %d, %s, %s, 100, \'cash\', %d, '
                   u'1, 0, 0, 0, \'%d\', NOW() FROM DUAL WHERE EXISTS (SELECT 1 FROM world.item_proto WHERE vnum = %d) '
                   u'AND NOT EXISTS (SELECT 1 FROM itemshop.ishop_items WHERE vnum = %d);\n' % (
                       1000000 + it['vnum'], WEB_CATEGORY[it['kind']], q(name), q(desc), it['vnum'], it['vnum'],
                       it['vnum'], it['vnum']))
    return u''.join(out)


def set_kind_counts(s):
    """How many lines of each kind a set of azcostume_sets (the tuple) has."""
    key, name, word, bodies, hairs, hair_word, first_weapon, back = s
    return {'ShapeData': len(bodies), 'HairData': len(hairs), 'Weapon': 6 if first_weapon else 0,
            'SashSkin': 1 if back else 0}


def ishop_index_base():
    """MT2009_PLUS_AREZZO_COSTUME_SETS_V2: the first in-game ItemShop index of each set's kind, counted in
    the V1 order of all 22 sets - a removed set leaves its indexes empty and every other line keeps the
    index V1 gave it (the block below ran once on every world that has the sets)."""
    by_key = dict((s[0], s) for s in A.SETS + A.REMOVED_SETS)
    n = dict(ISHOP_BASE)
    first = {}
    for key in A.SETS_V1_ORDER:
        counts = set_kind_counts(by_key[key])
        first[key] = dict(n)
        for kind, c in counts.items():
            n[kind] += c
    return first


def ishop_lines(items):
    first = ishop_index_base()
    n = {}
    rows = []
    for it in items:
        k = (it['set'], it['kind'])
        idx = first[it['set']][it['kind']] + n.get(k, 0)
        n[k] = n.get(k, 0) + 1
        rows.append(u"(%d, %d, 1, 100, 'DRAGON_COIN', 0)" % (idx, it['vnum']))
    return rows


def ishop_indexes(items):
    return [int(r[1:].split(',')[0]) for r in ishop_lines(items)]


def apply_block(items):
    rows = ishop_lines(items)
    return (u'# >>> %s (generated by gen_azcostume_server.py - do not edit by hand)\n'
            u'# The Arezzo costume sets (client-patches/client-2.0.30/tools/azcostume): the items, every start\n'
            u'# (INSERT IGNORE - a row the operator changed is kept; arezzo_costumes.sql), the in-game ItemShop\n'
            u'# lines once per install like our costumes (100 SM; hairs 10600+, costumes 20600+, weapon skins\n'
            u'# 30600+, sash skins 30800+ in "Nakladki"), and the web shop offers (arezzo_costumes_webshop.sql).\n'
            u'# %s: shown and sold only while the Arezzo module is on (mt2009_arezzo_closed; the engine\'s\n'
            u'# ItemShop, the bots and the web shop read it live - playerbot_arezzo_costumes.h, arezzo_costumes.php).\n'
            u'if [ -s /opt/playerbot/arezzo_costumes.sql ]; then\n'
            u'    db < /opt/playerbot/arezzo_costumes.sql || fail_step "could not add the Arezzo costume sets (arezzo_costumes.sql)" >&2\n'
            u'fi\n'
            u'if [ "$(db -e "SELECT COUNT(*) FROM world.item_proto WHERE vnum IN (%d, %d);" 2>/dev/null || echo x)" = "2" ]; then\n'
            u'ishop_once arezzo_costume_sets "INSERT IGNORE INTO common.itemshop_items (\\`index\\`, vnum, count, price, currency, minLevel) VALUES\n'
            u'%s;" "could not add the Arezzo costume sets to the ItemShop"\n'
            u'%s'
            u'fi\n'
            u'if [ -s /opt/playerbot/arezzo_costumes_webshop.sql ]; then\n'
            u'    db < /opt/playerbot/arezzo_costumes_webshop.sql 2>/dev/null || echo "[playerbot-migrate] note: no web ItemShop tables for the Arezzo costume sets" >&2\n'
            u'fi\n'
            u'%s'
            u'# <<< %s\n') % (MARK, MARK2, items[0]['vnum'], items[-1]['vnum'], u',\n'.join(rows), restored_block(items),
                             removed_block(), MARK)


def removed_block():
    """MT2009_PLUS_AREZZO_COSTUME_SETS_V4: single items taken out (azcostume_sets.REMOVED_ITEMS - the sash skins
    with Arezzo's "me_w" wings) - gone from every place V1 put them, idempotent: the item rows (every start,
    cheap), the in-game ItemShop lines (ishop_once), the web shop's offers and, once (azcostume_removed_v4),
    what players hold: their copies (and unopened ItemShop deliveries) are deleted, a sash wearing one of
    these skins gets socket2 = 0 back (it looks like the plain sash; bonuses / absorption unchanged)."""
    vn = A.removed_vnums()
    if not vn:
        return u''
    lst = u', '.join(str(v) for v in vn)
    skins = u', '.join(str(v) for v in vn if 85200 <= v <= 85299) or u'0'
    return (u'# %s: the sash skins with Arezzo\'s "me_w" wings are out (owner, 7 October: they cannot be\n'
            u'# placed right, the animation looks blocky) - %d items; the rest of their sets stays.\n'
            u'db -e "DELETE FROM world.item_proto WHERE vnum IN (%s);" || fail_step "could not remove the dropped Arezzo sash skins\' items" >&2\n'
            u'ishop_once arezzo_costume_sets_v4 "DELETE FROM common.itemshop_items WHERE vnum IN (%s);" "could not remove the dropped Arezzo sash skins from the ItemShop"\n'
            u'db -e "DELETE FROM itemshop.ishop_items WHERE vnum IN (%s);" 2>/dev/null || true\n'
            u'az_rm_done=$(db -e "SELECT COUNT(*) FROM player.playerbot_migrations WHERE name = \'azcostume_removed_v4\';" 2>/dev/null || echo x)\n'
            u'if [ "$az_rm_done" = "0" ]; then\n'
            u'    az_rm_items=$(db -e "SELECT COUNT(*) FROM player.item WHERE vnum IN (%s);" 2>/dev/null || echo "?")\n'
            u'    az_rm_skins=$(db -e "SELECT COUNT(*) FROM player.item i JOIN world.item_proto p ON p.vnum = i.vnum WHERE p.type = 28 AND p.subtype = 3 AND i.socket2 IN (%s);" 2>/dev/null || echo "?")\n'
            u'    if db -e "DELETE FROM player.item WHERE vnum IN (%s);\n'
            u'        UPDATE player.item i JOIN world.item_proto p ON p.vnum = i.vnum SET i.socket2 = 0 WHERE p.type = 28 AND p.subtype = 3 AND i.socket2 IN (%s);\n'
            u'        INSERT IGNORE INTO player.playerbot_migrations (name, done_at) VALUES (\'azcostume_removed_v4\', NOW());"; then\n'
            u'        db -e "DELETE FROM player.item_award WHERE vnum IN (%s);" 2>/dev/null || true\n'
            u'        echo "[playerbot-migrate] Arezzo costume sets V4: removed $az_rm_items held sash skin(s) 85213/85219/85220/85221, $az_rm_skins sash skin(s) taken off sashes"\n'
            u'    else\n'
            u'        fail_step "could not remove the players\' copies of the dropped Arezzo sash skins" >&2\n'
            u'    fi\n'
            u'fi\n') % (MARK4, len(vn), lst, lst, lst, lst, skins, lst, skins, lst)


def restored_block(items):
    """MT2009_PLUS_AREZZO_COSTUME_SETS_V3: the sets V2 removed and V3 brought back (azcostume_sets.RESTORED_V3)
    - their in-game ItemShop lines once more, at their V1 indexes, for a world where V2's ishop_once deleted
    them (INSERT IGNORE: a world that never ran V2 has them from the block above). Nothing deletes them any
    more: V2's every-start DELETEs and its one-off clean-up of the players' items are gone."""
    lines = ishop_lines(items)
    rows = [r for it, r in zip(items, lines) if it['set'] in A.RESTORED_V3]
    if not rows:
        return u''
    return (u'# %s: Ognisty Rycerz and Krwawa Zemsta are back (their effects work now) - their ItemShop\n'
            u'# lines once more where V2 removed them.\n'
            u'ishop_once arezzo_costume_sets_v3 "INSERT IGNORE INTO common.itemshop_items (\\`index\\`, vnum, count, price, currency, minLevel) VALUES\n'
            u'%s;" "could not give the ItemShop back the Arezzo sets Ognisty Rycerz and Krwawa Zemsta"\n') % (
        MARK3, u',\n'.join(rows))


def put_block(path, block, anchor):
    text = open(path, encoding='utf-8', newline='').read()
    assert '\r\n' not in text, path
    start, end = u'# >>> %s' % MARK, u'# <<< %s\n' % MARK
    if start in text:
        a = text.index(start)
        b = text.index(end, a) + len(end)
        text = text[:a] + block + text[b:]
    else:
        assert text.count(anchor) == 1, anchor
        text = text.replace(anchor, block + anchor)
    open(path, 'w', encoding='utf-8', newline='').write(text)


def costume_sets_txt(path, sets):
    raw = open(path, encoding='utf-8', newline='').read()
    nl = '\r\n' if '\r\n' in raw else '\n'
    lines = raw.replace('\r\n', '\n').split('\n')
    names = set(s['name'] for s in sets) | set(r[1] for r in A.REMOVED_SETS)   # V2: the removed ones go too
    keep = [l for l in lines if l.split('\t')[0] not in names and MARK not in l]
    while keep and keep[-1] == '':
        keep.pop()
    keep.append(u'# %s: the Arezzo costume sets (client-patches/client-2.0.30/tools/azcostume) - a costume (m)/(k)'
                % MARK)
    keep.append(u'# and a helmet (m)/(k) of one set give the same bonus as every set here; weapon / sash skins are looks only (%s).' % MARK)
    for s in sets:
        keep.append(u'%s\t%s\t%s' % (s['name'], ','.join(str(v) for v in s['bodies']), ','.join(str(v) for v in s['hairs'])))
    open(path, 'w', encoding='utf-8', newline='').write(nl.join(keep) + nl)
    return keep


def costume_sets_py(path, txt_lines):
    """SETS = (...) of root/costume_sets.py again from costume_sets.txt (its header and the code after stay)."""
    text = open(path, encoding='latin-1', newline='').read()
    assert '\r\n' not in text, path
    a = text.index('SETS = (\n')
    b = text.index('\n)\n', a) + 3
    rows = []
    for l in txt_lines:
        if not l or l.startswith('#'):
            continue
        name, bodies, hairs = l.split('\t')[:3]
        rows.append('\t((%s,), (%s,)),\t# %s' % (bodies, hairs, name))
    text = text[:a] + 'SETS = (\n' + '\n'.join(rows) + '\n)\n' + text[b:]
    open(path, 'w', encoding='latin-1', newline='').write(text)


# --- MT2009_PLUS_AREZZO_COSTUME_SETS_V2: the sets only while the Arezzo module is on ---------------
# One world switch, the event flag mt2009_arezzo_closed (1 = off; apply.sh from M2_AREZZO, the panel's
# "Modul Arezzo" live) - the same one the maps, dungeons and guards follow (playerbot_arezzo.h).
ENGINE_LIST = 'linux-port/overlays/playerbot/src/game/src/playerbot_arezzo_costumes.h'


def write_engine_list(path, items):
    vn = sorted(it['vnum'] for it in items)
    rows = []
    for i in range(0, len(vn), 12):
        rows.append('\t\t' + ', '.join(str(v) for v in vn[i:i + 12]) + ',')
    text = (u'// %s (generated by client-patches/client-2.0.30/tools/azcostume/gen_azcostume_server.py from\n'
            u'// azcostume_items.json - do not edit by hand): the Arezzo costume sets\' items (%d) are for sale only\n'
            u'// while the Arezzo module is on - the event flag mt2009_arezzo_closed (1 = off), the switch\n'
            u'// playerbot_arezzo.h follows. Read by the engine\'s ItemShop (server-patches/azcostume, (ishop-list) / (ishop-buy)):\n'
            u'// CItemShopManager::CanSendItem leaves the line out of the window, BuyItem refuses it) and by the\n'
            u'// bots\' catalogue (playerbot_itemshop.h, which includes this file exactly once). The item rows\n'
            u'// stay in item_proto: what a player already holds keeps working.\n'
            u'#ifndef __INC_MT2009_PLUS_AREZZO_COSTUMES_H__\n'
            u'#define __INC_MT2009_PLUS_AREZZO_COSTUMES_H__\n'
            u'\n'
            u'#include <algorithm>\n'
            u'#include "questmanager.h"\n'
            u'\n'
            u'namespace mt2009_arezzo_costumes\n'
            u'{\n'
            u'\tconst DWORD VNUMS[] = {\n'
            u'%s\n'
            u'\t};\n'
            u'\n'
            u'\tinline bool IsItem(DWORD vnum)\n'
            u'\t{\n'
            u'\t\treturn std::binary_search(VNUMS, VNUMS + sizeof(VNUMS) / sizeof(VNUMS[0]), vnum);\n'
            u'\t}\n'
            u'\n'
            u'\tinline bool ModuleClosed()\n'
            u'\t{\n'
            u'\t\treturn quest::CQuestManager::instance().GetEventFlag("mt2009_arezzo_closed") > 0;\n'
            u'\t}\n'
            u'}\n'
            u'\n'
            u'// The engine\'s side (itemshop_manager.cpp declares it): an Arezzo set item while the module is off.\n'
            u'bool Mt2009PlusArezzoCostumeLocked(DWORD vnum)\n'
            u'{\n'
            u'\treturn mt2009_arezzo_costumes::IsItem(vnum) && mt2009_arezzo_costumes::ModuleClosed();\n'
            u'}\n'
            u'\n'
            u'#endif\n') % (MARK2, len(vn), '\n'.join(rows))
    open(path, 'w', encoding='utf-8', newline='\n').write(text)


def web_gate_php(items):
    vn = ','.join(str(v) for v in sorted(it['vnum'] for it in items))
    return (u'<?php\n'
            u'// %s (generated by client-patches/client-2.0.30/tools/azcostume/gen_azcostume_server.py - do not\n'
            u'// edit by hand): the Arezzo costume sets are offered only while the Arezzo module is on - the world\n'
            u'// flag mt2009_arezzo_closed (player.quest, dwPID 0; 1 = off, written by apply.sh from M2_AREZZO and\n'
            u'// live by the panel\'s "Modul Arezzo"). No row reads as off, as the panel reads it. index.php\n'
            u'// loads this; home / category / detail leave the offers out, buy refuses them.\n'
            u"define('MT2009_AREZZO_COSTUME_VNUMS', '%s');\n"
            u'\n'
            u'function mt2009_arezzo_closed($sqlServ) {\n'
            u'\tstatic $closed = null;\n'
            u'\tif ($closed === null) {\n'
            u'\t\t$row = null;\n'
            u'\t\ttry {   // PHP 8.1+ throws on a failed query; a flag nobody can read keeps the sets hidden\n'
            u'\t\t\t$r = mysqli_query($sqlServ, "SELECT lValue FROM player.quest WHERE dwPID = 0 AND szName = \'mt2009_arezzo_closed\' LIMIT 1");\n'
            u'\t\t\t$row = $r ? mysqli_fetch_row($r) : null;\n'
            u'\t\t} catch (Throwable $e) {\n'
            u'\t\t\t$row = null;\n'
            u'\t\t}\n'
            u'\t\t$closed = !$row || (int)$row[0] > 0;\n'
            u'\t}\n'
            u'\treturn $closed;\n'
            u'}\n'
            u'\n'
            u'// " AND <col> NOT IN (...)" while the module is off, "" while it is on.\n'
            u"function mt2009_arezzo_costume_sql($sqlServ, $col = 'vnum') {\n"
            u"\treturn mt2009_arezzo_closed($sqlServ) ? ' AND ' . $col . ' NOT IN (' . MT2009_AREZZO_COSTUME_VNUMS . ')' : '';\n"
            u'}\n'
            u'\n'
            u'function mt2009_arezzo_costume_locked($sqlServ, $vnum) {\n'
            u"\treturn in_array((string)(int)$vnum, explode(',', MT2009_AREZZO_COSTUME_VNUMS), true) && mt2009_arezzo_closed($sqlServ);\n"
            u'}\n') % (MARK2, vn)


# --- icons for the web shop: TGA (types 2/10, 24/32 bit) or PNG -> PNG --------------------------
def tga_rgba(b):
    idlen, cmtype, itype = b[0], b[1], b[2]
    w, h, bpp, desc = struct.unpack_from('<HHBB', b, 12)
    assert cmtype == 0 and itype in (2, 10) and bpp in (24, 32), (cmtype, itype, bpp)
    px = bpp // 8
    pos = 18 + idlen
    data = bytearray()
    need = w * h * px
    if itype == 2:
        data = b[pos:pos + need]
    else:
        while len(data) < need:
            c = b[pos]
            pos += 1
            n = (c & 0x7f) + 1
            if c & 0x80:
                data += b[pos:pos + px] * n
                pos += px
            else:
                data += b[pos:pos + px * n]
                pos += px * n
    rows = []
    for y in range(h):
        sy = y if desc & 0x20 else h - 1 - y
        row = bytearray()
        for x in range(w):
            p = data[(sy * w + x) * px:(sy * w + x + 1) * px]
            row += bytes((p[2], p[1], p[0], p[3] if px == 4 else 255))
        rows.append(bytes(row))
    return w, h, rows


def png_bytes(w, h, rows):
    def chunk(t, d):
        return struct.pack('>I', len(d)) + t + d + struct.pack('>I', zlib.crc32(t + d) & 0xffffffff)
    raw = b''.join(b'\0' + r for r in rows)
    return (b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', w, h, 8, 6, 0, 0, 0)) +
            chunk(b'IDAT', zlib.compress(raw, 9)) + chunk(b'IEND', b''))


def web_icon(icon_key):
    src = os.path.join(ICON_SRC, icon_key)
    b = open(src, 'rb').read()
    if b[:8] == b'\x89PNG\r\n\x1a\n':
        return b
    return png_bytes(*tga_rgba(b))


def main():
    if len(sys.argv) != 2:
        raise SystemExit('usage: gen_azcostume_server.py <repo>')
    repo = sys.argv[1]
    d = load()
    items = d['items']
    pb = os.path.join(repo, 'linux-port/docker/mariadb/playerbot')
    open(os.path.join(pb, 'arezzo_costumes.sql'), 'w', encoding='utf-8').write(sql_items(items))
    open(os.path.join(pb, 'arezzo_costumes_webshop.sql'), 'w', encoding='utf-8').write(sql_web(items))
    put_block(os.path.join(pb, 'apply.sh'), apply_block(items), u'# MT2009_PLUS_COLLECTOR_STORAGE_V1: the collector\'s storage (Magazyn\n')
    txt = costume_sets_txt(os.path.join(repo, 'linux-port/docker/game/costume_sets.txt'), d['sets'])
    costume_sets_py(os.path.join(repo, 'client-patches/client-2.0.30/root/costume_sets.py'), txt)
    img = os.path.join(repo, 'linux-port/docker/itemshop/app/itemshop/img/item')
    made = 0
    if os.path.isdir(ICON_SRC):
        for it in items:
            dst = os.path.join(img, '%d.png' % it['vnum'])
            png = web_icon(it['icon'])
            if not os.path.exists(dst) or open(dst, 'rb').read() != png:
                open(dst, 'wb').write(png)
                made += 1
    gone = 0
    for v in A.removed_vnums():   # MT2009_PLUS_AREZZO_COSTUME_SETS_V2: the removed sets' icons
        dst = os.path.join(img, '%d.png' % v)
        if os.path.exists(dst):
            os.remove(dst)
            gone += 1
    open(os.path.join(repo, 'linux-port/docker/itemshop/app/itemshop/arezzo_costumes.php'), 'w',
         encoding='utf-8').write(web_gate_php(items))
    write_engine_list(os.path.join(repo, ENGINE_LIST), items)
    print('items %d, ItemShop lines %d, sets %d, web icons written %d, removed %d' % (
        len(items), len(ishop_lines(items)), len(d['sets']), made, gone))


if __name__ == '__main__':
    main()
