#!/usr/bin/env python3
"""gen_wikinowe_sql.py - MT2009_PLUS_NS_WIKI_ITEMS_V1 (Autor: Digi Rasta, nowy-system 0.33.0, his
narzedzia/wiki_nowe.py and 95_wiki_nowe.sql in the fixed 0.35.0 form with USE world): the item families and
upgrade materials of the official PL wiki our world did not have, written from wiki_nowe.json (his
dane/wiki_nowe.json without the Zodiac families - those are zodiak.sql's - and with our stack of 200 for the
16 materials instead of his 1000) into linux-port/docker/mariadb/playerbot/wiki_nowe.sql:

  item_proto    116 rows: Cyjanitowy Miecz 500 / Sztylet 1500 / Luk 2500 / Ostrze 3500 / Dzwon 5500 /
                Wachlarz 7500, Bransoleta 14570 / Naszyjnik 16570 z Turmalinu, Ogniste Buty 15440, Buty Oceanu
                15450 (+0..+9 each) and 16 materials (30602-30604, 30610, 30616-30618, 30623, 30624,
                30626, 30627, 30629, 50639, 95601-95603);
  refine_proto  22310-22338 (29 steps; the other steps reuse the world's own 2, 182-184, 404).

Idempotent, every start: a row of ours (the same vnum and the same name) is deleted and written again; a row
of that vnum with another name (the mod made the item its own) stays and ours does not go in (INSERT IGNORE).
The client's records come from the same json (client-patches/client-2.0.30/tools/wikinowe).

    python3 tools/wikinowe/gen_wikinowe_sql.py [<out .sql>]
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, '..', '..'))
OUT = os.path.join(REPO, 'linux-port', 'docker', 'mariadb', 'playerbot', 'wiki_nowe.sql')
REFINE_COLS = ('id', 'vnum0', 'count0', 'vnum1', 'count1', 'vnum2', 'count2', 'vnum3', 'count3', 'vnum4', 'count4',
               'cost', 'src_vnum', 'result_vnum', 'prob')


def q(v):
    if isinstance(v, int):
        return str(v)
    return "'" + str(v).replace('\\', '\\\\').replace("'", "''") + "'"


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else OUT
    d = json.load(open(os.path.join(HERE, 'wiki_nowe.json'), encoding='utf-8'))
    cols = d['kolumny']
    items = [d['items'][k] for k in sorted(d['items'], key=int)]
    refine = [d['refine'][k] for k in sorted(d['refine'], key=int)]
    assert len(items) == 116 and len(refine) == 29, (len(items), len(refine))
    for w in items:
        assert len(w['locale_name'].encode('cp1250')) < 32 and len(w['name'].encode('cp1250')) < 32, w['vnum']
        assert w['stack'] == 200, w['vnum']
    ids = set(r['id'] for r in refine)
    assert min(ids) >= 22301 and max(ids) <= 22399, sorted(ids)
    L = []
    L.append('-- MT2009_PLUS_NS_WIKI_ITEMS_V1 (Autor: Digi Rasta, nowy-system 0.33.0): the item families and upgrade')
    L.append('-- materials of the official PL wiki our world did not have. Generated by tools/wikinowe/gen_wikinowe_sql.py')
    L.append('-- from tools/wikinowe/wiki_nowe.json - do not edit. Run by apply.sh at every start; idempotent: only our own')
    L.append('-- rows (the same vnum and name) are deleted and written again, a row the mod made with another name stays.')
    L.append('SET NAMES utf8mb4;')
    L.append('USE world;')
    L.append('')
    L.append('CREATE TEMPORARY TABLE tmp_wikinowe_names (vnum INT UNSIGNED NOT NULL PRIMARY KEY, locale_name VARCHAR(32) CHARACTER SET cp1250 NOT NULL);')
    L.append('INSERT INTO tmp_wikinowe_names VALUES')
    L.append(',\n'.join('(%d,%s)' % (w['vnum'], q(w['locale_name'])) for w in items) + ';')
    L.append('DELETE p FROM world.item_proto p JOIN tmp_wikinowe_names t ON t.vnum = p.vnum AND BINARY t.locale_name = BINARY p.locale_name;')
    L.append('DROP TEMPORARY TABLE tmp_wikinowe_names;')
    L.append('INSERT IGNORE INTO world.item_proto (%s) VALUES' % ','.join('`%s`' % c for c in cols))
    L.append(',\n'.join('(' + ','.join(q(w[c]) for c in cols) + ')' for w in items) + ';')
    L.append('')
    L.append('INSERT INTO world.refine_proto (%s) VALUES' % ', '.join(REFINE_COLS))
    L.append(',\n'.join('(' + ', '.join(str(int(r[c])) for c in REFINE_COLS) + ')' for r in refine))
    L.append('ON DUPLICATE KEY UPDATE ' + ', '.join('%s = VALUES(%s)' % (c, c) for c in REFINE_COLS[1:]) + ';')
    data = ('\n'.join(L) + '\n').encode('utf-8')
    old = open(out, 'rb').read() if os.path.exists(out) else None
    if old != data:
        open(out, 'wb').write(data)
    print('%s: %d items, %d refine steps%s' % (os.path.relpath(out, REPO), len(items), len(refine), '' if old != data else ' (unchanged)'))


if __name__ == '__main__':
    main()
