<?php
// MT2009_PLUS_AREZZO_COSTUME_SETS_V2 (generated by client-patches/client-2.0.30/tools/azcostume/gen_azcostume_server.py - do not
// edit by hand): the Arezzo costume sets are offered only while the Arezzo module is on - the world
// flag mt2009_arezzo_closed (player.quest, dwPID 0; 1 = off, written by apply.sh from M2_AREZZO and
// live by the panel's "Modul Arezzo"). No row reads as off, as the panel reads it. index.php
// loads this; home / category / detail leave the offers out, buy refuses them.
define('MT2009_AREZZO_COSTUME_VNUMS', '40600,40601,40602,40603,40604,40605,40700,40701,40702,40703,40704,40705,40710,40711,40712,40713,40714,40715,40800,40801,40802,40803,40804,40805,40810,40811,40812,40813,40814,40815,40820,40821,40822,40823,40824,40825,40830,40831,40832,40833,40834,40835,40840,40841,40842,40843,40844,40845,40850,40851,40852,40853,40854,40855,40860,40861,40862,40863,40864,40865,40870,40871,40872,40873,40874,40875,40880,40881,40882,40883,40884,40885,40900,40901,40902,40903,40904,40905,40910,40911,40912,40913,40914,40915,40920,40921,40922,40923,40924,40925,40940,40941,40942,40943,40944,40945,40950,40951,40952,40953,40954,40955,40960,40961,40962,40963,40964,40965,40970,40971,40972,40973,40974,40975,40980,40981,40982,40983,40984,40985,40990,40991,40992,40993,40994,40995,42900,42901,42904,42905,42908,42909,42924,42925,42926,42927,42928,42929,42930,42931,42932,42933,42934,42935,42936,42937,42938,42939,42940,42941,42942,42943,42944,42945,42946,42947,42948,42949,42950,42951,42952,42953,42954,42955,42958,42959,42960,42961,42962,42963,45900,45901,45904,45905,45908,45909,45924,45925,45926,45927,45928,45929,45930,45931,45932,45933,45934,45935,45936,45937,45938,45939,45940,45941,45942,45943,45944,45945,45946,45947,45948,45949,45950,45951,45952,45953,45954,45955,45958,45959,45960,45961,45962,45963,85200,85201,85202,85203,85204,85205,85206,85207,85208,85209,85210,85211,85212,85214,85215,85216,85217');

function mt2009_arezzo_closed($sqlServ) {
	static $closed = null;
	if ($closed === null) {
		$row = null;
		try {   // PHP 8.1+ throws on a failed query; a flag nobody can read keeps the sets hidden
			$r = mysqli_query($sqlServ, "SELECT lValue FROM player.quest WHERE dwPID = 0 AND szName = 'mt2009_arezzo_closed' LIMIT 1");
			$row = $r ? mysqli_fetch_row($r) : null;
		} catch (Throwable $e) {
			$row = null;
		}
		$closed = !$row || (int)$row[0] > 0;
	}
	return $closed;
}

// " AND <col> NOT IN (...)" while the module is off, "" while it is on.
function mt2009_arezzo_costume_sql($sqlServ, $col = 'vnum') {
	return mt2009_arezzo_closed($sqlServ) ? ' AND ' . $col . ' NOT IN (' . MT2009_AREZZO_COSTUME_VNUMS . ')' : '';
}

function mt2009_arezzo_costume_locked($sqlServ, $vnum) {
	return in_array((string)(int)$vnum, explode(',', MT2009_AREZZO_COSTUME_VNUMS), true) && mt2009_arezzo_closed($sqlServ);
}
