"""Enum vocabularies for log.playerbot_listing/log.playerbot_equip's decision
codes (Playerbots 2.2.39+, "the bots' explained decisions"). Extracted
programmatically (AST parse + exec, then de/tr keys stripped) from the upstream
classic admin_panel.py, the reference implementation -- not
hand-transcribed, so these numbers and their pl/en wording match it exactly.
See decisions.py for the decode logic that uses these."""

DECISION_EVENTS = {0: {'pl': 'Nieznane zdarzenie', 'en': 'Unknown event'},
 1: {'pl': 'Wystawione przy otwarciu sklepu', 'en': 'Listed when the shop opened'},
 2: {'pl': 'Dołożone przy obsłudze sklepu', 'en': 'Added on a shop visit'},
 3: {'pl': 'Wystawione na straganie', 'en': 'Listed on a stall'},
 4: {'pl': 'Przecenione', 'en': 'Repriced'},
 5: {'pl': 'Pomyłka w cenie poprawiona przez właściciela', 'en': 'Price slip put right by the keeper'},
 6: {'pl': 'Pomyłka w cenie poprawiona przez rdzeń', 'en': 'Price slip put right by the core'},
 7: {'pl': 'Podniesione do progu', 'en': 'Raised to the floor'},
 8: {'pl': 'Zdjęte z lady', 'en': 'Taken off the counter'},
 9: {'pl': 'Zabrane z lady do założenia', 'en': 'Taken back to wear'},
 10: {'pl': 'Sprzedane', 'en': 'Sold'}}

DECISION_STAND = {0: {'pl': 'powód nieznany', 'en': 'reason unknown'},
 1: {'pl': 'osobowość Handlarz', 'en': 'the Merchant personality'},
 2: {'pl': 'brak yang na mikstury', 'en': 'no yang for potions'},
 3: {'pl': 'pełny plecak', 'en': 'a full bag'},
 4: {'pl': 'dropper z pełnym plecakiem', 'en': 'a dropper with a full bag'},
 5: {'pl': 'nadmiar ksiąg', 'en': 'too many books'},
 6: {'pl': 'los droppera', 'en': "a dropper's roll"},
 7: {'pl': 'los', 'en': 'chance'},
 8: {'pl': 'zbędny duplikat', 'en': 'a spare duplicate'},
 9: {'pl': 'nadmiar towaru', 'en': 'surplus goods'}}

DECISION_SHAPES = {0: {'pl': 'cały stos', 'en': 'the whole stack'},
 1: {'pl': 'naturalna porcja', 'en': 'a natural lot'},
 2: {'pl': 'paczka mikstur', 'en': 'a potion pack'},
 3: {'pl': 'paczka pyłu', 'en': 'a dust pack'},
 4: {'pl': 'para medali', 'en': 'a pair of medals'},
 5: {'pl': 'sztuka ponad zapas', 'en': 'a single over the keep'},
 6: {'pl': 'pojedynczy klucz', 'en': 'a single key'},
 7: {'pl': 'paczka szkatułek', 'en': 'a chest pack'},
 8: {'pl': 'sztuka oddzielona na straganie', 'en': 'a single split off for a stall'}}

DECISION_OFF = {0: {'pl': 'bez podanego powodu', 'en': 'no reason given'},
 1: {'pl': 'Lista Przydatnych Przedmiotów zatrzymuje go dla magazyniera',
     'en': 'the Useful Items List keeps it for the storekeeper'},
 2: {'pl': 'kamień duszy dla Alchemika (na pył)', 'en': "a spirit stone for the Alchemist's dust"},
 3: {'pl': 'za dużo marmurów albo drugi tego samego potwora', 'en': 'too many marbles, or a second of one monster'},
 4: {'pl': 'ponad limit linii tego samego przedmiotu', 'en': 'over the line cap of one item'},
 5: {'pl': 'za dużo ksiąg misji w wiosce', 'en': 'too many mission books in the village'},
 6: {'pl': 'za dużo słabych broni na ladach', 'en': 'too many junk weapons on the counters'},
 7: {'pl': 'niepełna paczka mikstur, do zlania', 'en': 'not a whole potion pack, to be poured together'},
 8: {'pl': 'za dużo słabych zbroi tej rodziny', 'en': 'too many low armours of this family'},
 9: {'pl': 'za dużo słabej biżuterii tej rodziny', 'en': 'too many low jewels of this family'},
 10: {'pl': 'farba z wody, do wyrzucenia', 'en': 'a dye from the water, to be thrown away'},
 11: {'pl': 'broń 30 lv wraca pod kowadło', 'en': 'a level-30 weapon goes back to the anvil'},
 12: {'pl': 'szkatułki: bot ich nie sprzedaje albo linia za długa',
      'en': 'chests: the bot does not sell them, or the line is too long'},
 13: {'pl': 'za długa linia Kamieni Duchowych', 'en': 'too long a line of Soul Stones'},
 14: {'pl': 'linia zwojów nie po 1, 2 lub 5', 'en': 'a scroll line not of 1, 2 or 5'},
 15: {'pl': 'za długa linia medali konnych', 'en': 'too long a line of horse medals'},
 16: {'pl': 'sterta nie w naturalnej porcji', 'en': 'a heap not in a natural lot'},
 17: {'pl': 'materiał nie w naturalnej porcji', 'en': 'a material not in a natural lot'},
 18: {'pl': 'ekwipunek poniżej 30 lv za słaby albo ponad limit', 'en': 'gear under level 30 too low, or over its cap'},
 19: {'pl': 'wędka lub kilof wraca do właściciela', 'en': 'a rod or a pickaxe goes back to its owner'},
 20: {'pl': 'zabrane do założenia', 'en': 'taken back to wear'}}

DECISION_ENUMS = {'POLICY': {1: {'pl': 'zostaw', 'en': 'keep'},
            2: {'pl': 'stragan', 'en': 'stall'},
            3: {'pl': 'handlarz', 'en': 'merchant'},
            4: {'pl': 'wyrzuć', 'en': 'drop'}},
 'STALKI_WHY': {1: {'pl': 'innej klasy', 'en': "another class's"},
                2: {'pl': 'za daleko w przód', 'en': 'too far ahead'},
                3: {'pl': 'druga sztuka', 'en': 'a second copy'}},
 'L30_WHY': {1: {'pl': 'projekt', 'en': 'a project'},
             2: {'pl': 'broń własnej klasy', 'en': "the class's own"},
             3: {'pl': 'innej klasy', 'en': "another class's"},
             4: {'pl': 'losowanie wskazało ladę', 'en': 'the draw said counter'},
             5: {'pl': 'plecak trzyma już maksimum', 'en': 'the bag already keeps the maximum'},
             6: {'pl': 'zatrzymana losowaniem', 'en': 'kept by the draw'}},
 'SCROLL_KEEP': {0: {'pl': 'nic nie czeka na zwój', 'en': 'nothing waits for a scroll'},
                 1: {'pl': 'noszony ekwipunek do ulepszenia', 'en': 'worn gear to refine'},
                 2: {'pl': 'handlarz zasobami', 'en': 'a resource trader'},
                 3: {'pl': 'reguła zwojów', 'en': 'the scroll rule'}},
 'MEDAL_WHY': {1: {'pl': 'Handlarz', 'en': 'a Merchant'},
               2: {'pl': 'dropper medali', 'en': 'a medal dropper'},
               3: {'pl': 'ponad zapas', 'en': 'over the keep'},
               4: {'pl': 'koń na maksimum dla poziomu', 'en': 'the horse is maxed for the level'}},
 'MAT_WHY': {1: {'pl': 'próba rynku', 'en': 'a market probe'},
             2: {'pl': 'brak popytu', 'en': 'no demand'},
             3: {'pl': 'nadmiar', 'en': 'overstock'}},
 'VALUABLE': {0: {'pl': '', 'en': ''}, 1: {'pl': ' (z cennym bonusem)', 'en': ' (with a valuable bonus)'}},
 'BOOK_USEFUL': {0: {'pl': ' (bot jej nie przeczyta)', 'en': ' (of no use to the bot)'},
                 1: {'pl': ' (przydatna, ale ponad zapas)', 'en': ' (useful, but over the keep)'}},
 'AT_TOP': {0: {'pl': '', 'en': ''}, 1: {'pl': ' (na maksimum)', 'en': ' (at the top)'}},
 'PREVIEW': {0: {'pl': '', 'en': ''},
             1: {'pl': ' (podgląd bez właściciela, więc bez wahania)',
                 'en': ' (a preview without its keeper, so no swing)'}},
 'MARBLE_SRC': {0: {'pl': 'losowanie z przedziału', 'en': 'drawn from the band'},
                1: {'pl': 'wyjątek wymieniony z nazwy', 'en': 'a named exception'}},
 'FIXED': {1: {'pl': 'biała perła', 'en': 'white pearl'},
           2: {'pl': 'niebieska perła', 'en': 'blue pearl'},
           3: {'pl': 'czerwona perła', 'en': 'red pearl'},
           4: {'pl': 'małża', 'en': 'shellfish'},
           5: {'pl': 'medal konny', 'en': 'horse medal'},
           6: {'pl': 'Suszona Głowa', 'en': 'Dried Head'},
           7: {'pl': 'fryzura', 'en': 'hairstyle'},
           8: {'pl': 'Magiczny Pył', 'en': 'Magic Dust'}},
 'GRADE_TABLE': {0: {'pl': '', 'en': ''}, 1: {'pl': ' (z tabeli stopni)', 'en': ' (from the grade table)'}},
 'CLOCK_UNIT': {0: {'pl': 'wystawień', 'en': 'stands'}, 1: {'pl': 'min', 'en': 'min'}},
 'CLOCK_RESTART': {0: {'pl': '', 'en': ''},
                   1: {'pl': ' (zegar ruszył po restarcie)', 'en': ' (the clock began after a restart)'}},
 'GENERATION': {0: {'pl': 'bieżące pokolenie', 'en': 'the current generation'},
                1: {'pl': 'wycenione w innym pokoleniu (nadrabia tempo)',
                    'en': 'priced under another generation (catching up)'}},
 'SLIP_BY': {0: {'pl': 'poprawił właściciel', 'en': 'the keeper put it right'},
             1: {'pl': 'poprawił rdzeń, bo właściciel był daleko',
                 'en': 'the core put it right, the keeper being away'},
             2: {'pl': 'poprawił rdzeń, bo pomyłka była wstrzymana',
                 'en': 'the core put it right, the slip being held'},
             3: {'pl': 'poprawił rdzeń, po czasie', 'en': 'the core put it right, late'}},
 'LADDER_CAT': {1: {'pl': 'broń', 'en': 'weapon'},
                2: {'pl': 'zbroja', 'en': 'armour'},
                3: {'pl': 'tarcza', 'en': 'shield'},
                4: {'pl': 'hełm', 'en': 'helmet'},
                5: {'pl': 'buty', 'en': 'boots'},
                6: {'pl': 'bransoleta', 'en': 'bracelet'},
                7: {'pl': 'naszyjnik', 'en': 'necklace'},
                8: {'pl': 'kolczyki', 'en': 'earrings'},
                9: {'pl': 'broń zapasowa', 'en': 'backup weapon'},
                10: {'pl': 'zbroja zapasowa', 'en': 'backup armour'}},
 'SAFEBOX_WHY': {1: {'pl': 'Stalka', 'en': 'a Stalki'},
                 2: {'pl': 'zwolnione z Listy Przydatnych Przedmiotów', 'en': 'released from the Useful Items List'},
                 3: {'pl': 'hazard', 'en': 'a gamble'},
                 4: {'pl': 'klucz', 'en': 'a key'},
                 9: {'pl': 'inne', 'en': 'other'}}}

DECISION_GOODS = {0: ({}, {'pl': 'Wystawione, zanim zaczęto zapisywać wyjaśnienia', 'en': 'Listed before explanations were recorded'}),
 1: ({'a': 'enum:POLICY'},
     {'pl': 'Operator przypisał go ladzie (reguła „{a}”)', 'en': 'The operator sent it to the counter (rule “{a}”)'}),
 2: ({'a': 'plus'},
     {'pl': 'Towar hazardzisty z sesji przy kowadle ({a})',
      'en': "A gambler's goods from its session at the anvil ({a})"}),
 3: ({'a': 'int', 'b': 'int'},
     {'pl': 'Kamienie Duchowe ponad zapas: w plecaku {a}, zapas {b}',
      'en': 'Soul Stones over the keep: {a} in the bag, keeps {b}'}),
 4: ({'a': 'mob'},
     {'pl': 'Marmur polimorfii ({a}) — towar, nie złom', 'en': 'A polymorph marble ({a}) — goods, not scrap'}),
 5: ({},
     {'pl': 'Wykrywacz metinów — bot teraz nie poluje na kamienie',
      'en': 'A Metin detector — the bot is not hunting stones now'}),
 6: ({},
     {'pl': 'Suszona Głowa — dla graczy idących do Katakumb',
      'en': "A Dried Head — for a player's run of the Catacomb"}),
 7: ({'a': 'int', 'b': 'int'},
     {'pl': 'Kamienie bonusów ponad zapas: w plecaku {a}, zapas {b}',
      'en': 'Bonus stones over the keep: {a} in the bag, keeps {b}'}),
 8: ({'a': 'skill'},
     {'pl': 'Zwój Zapomnienia ({a}) z listy „do handlarki” — wystawia go tylko Handlarz',
      'en': 'A Forgetting Scroll ({a}) of the merchant-only list — only a Merchant lists it'}),
 9: ({'a': 'plus', 'b': 'level', 'c': 'enum:STALKI_WHY'},
     {'pl': 'Stalka, której bot nie zatrzymuje: {a}, poziom {b} — {c}',
      'en': 'A Stalki the bot does not keep: {a}, level {b} — {c}'}),
 10: ({'a': 'plus', 'b': 'pct', 'c': 'plus'},
      {'pl': 'Broń 30 lv innej klasy, gotowa na sprzedaż: {a}, średnie obrażenia {b}, cel {c}',
       'en': 'A level-30 weapon of another class, ready for sale: {a}, average damage {b}, target {c}'}),
 11: ({'a': 'plus', 'b': 'pct', 'c': 'enum:L30_WHY'},
      {'pl': 'Broń 30 lv niezatrzymana do kowadła: {a}, średnie obrażenia {b} — {c}',
       'en': 'A level-30 weapon not kept for the anvil: {a}, average damage {b} — {c}'}),
 12: ({'a': 'plus', 'b': 'level'},
      {'pl': 'Zbroja lub biżuteria {a} poniżej 30 lv (poziom {b}) — towar każdego bota',
       'en': "Armour or a jewel at {a} under level 30 (level {b}) — every bot's goods"}),
 13: ({'a': 'plus', 'b': 'plus', 'c': 'level'},
      {'pl': 'Ekwipunek poniżej 30 lv na minimalnym ulepszeniu: {a} (próg {b}), poziom {c}',
       'en': 'Gear under level 30 at its minimum refine: {a} (threshold {b}), level {c}'}),
 14: ({'a': 'plus', 'b': 'enum:VALUABLE'},
      {'pl': 'Nadwyżka z Listy Przydatnych Przedmiotów: {a}{b}', 'en': 'Surplus of the Useful Items List: {a}{b}'}),
 15: ({'a': 'apply', 'b': 'applyval:a'}, {'pl': 'Cenny bonus: {a} {b}', 'en': 'A valuable bonus: {a} {b}'}),
 16: ({'a': 'plus'},
      {'pl': 'Ekwipunek z listy „do handlarza” ({a}) — wystawia go tylko Handlarz',
       'en': 'Gear of the merchant-only list ({a}) — only a Merchant lists it'}),
 17: ({'a': 'plus', 'b': 'item', 'c': 'plus'},
      {'pl': 'Cenny zapas {a}; bot nosi {b} ({c})', 'en': 'A precious spare at {a}; the bot wears {b} ({c})'}),
 18: ({'a': 'int', 'b': 'int', 'c': 'enum:SCROLL_KEEP'},
      {'pl': 'Zwoje ponad zapas: {a} w plecaku, zapas {b} ({c})',
       'en': 'Scrolls over the keep: {a} in the bag, keeps {b} ({c})'}),
 19: ({'a': 'int', 'b': 'int', 'c': 'enum:MEDAL_WHY'},
      {'pl': 'Medale konne: {a} w plecaku, zapas {b} ({c})', 'en': 'Horse medals: {a} in the bag, keeps {b} ({c})'}),
 20: ({'a': 'int', 'b': 'int', 'c': 'int'},
      {'pl': 'Materiał, którego wiosce brakuje dla graczy: {a} w plecaku, rezerwa kowadła {b}, podaż w wiosce {c}',
       'en': 'A material the village is short of for the players: {a} in the bag, anvil reserve {b}, village supply '
             '{c}'}),
 21: ({'a': 'int', 'b': 'int', 'c': 'int'},
      {'pl': 'Materiał, którego brakuje botom: {a} w plecaku, rezerwa {b}, brakuje {c} botom',
       'en': 'A material the bots are short of: {a} in the bag, reserve {b}, {c} bots short'}),
 22: ({'a': 'int', 'b': 'int', 'c': 'enum:MAT_WHY'},
      {'pl': 'Materiał ponad rezerwę: {a} w plecaku, rezerwa {b} ({c})',
       'en': 'A material over the reserve: {a} in the bag, reserve {b} ({c})'}),
 23: ({'a': 'plus'},
      {'pl': 'Towar zebrany z ziemi (siano, marchew, księgi misji), {a}',
       'en': 'Pickup goods (hay, carrots, mission books), {a}'}),
 24: ({}, {'pl': 'Mikstura z tablicy Baek-Go ponad zapas', 'en': "A potion from Baek-Go's board, over the keep"}),
 25: ({}, {'pl': 'Receptura przeczytana do sufitu', 'en': 'A recipe already read to its ceiling'}),
 26: ({}, {'pl': 'Farba do włosów z ItemShopu', 'en': 'An item-shop hair dye'}),
 27: ({}, {'pl': 'Farba z wody zatrzymana na sprzedaż', 'en': 'A dye from the water kept for sale'}),
 28: ({}, {'pl': 'Fryzura z ItemShopu, której bot nie założy', 'en': 'An item-shop hairstyle the bot cannot wear'}),
 29: ({'a': 'skill'},
      {'pl': 'Zwój Zapomnienia — żadna umiejętność bota na niego nie czeka ({a})',
       'en': "A Forgetting Scroll — none of the bot's skills waits for it ({a})"}),
 30: ({'a': 'int', 'b': 'int'},
      {'pl': 'Magiczny Pył ponad zapas: {a} w plecaku, zapas {b}',
       'en': 'Magic Dust over the keep: {a} in the bag, keeps {b}'}),
 31: ({'a': 'plus', 'b': 'int'},
      {'pl': 'Kamień duszy {a} (rodzaj {b}) — jeden z 15 na 100 zostawionych dla rynku',
       'en': 'A spirit stone {a} (kind {b}) — one of the 15 in 100 kept for the market'}),
 32: ({'a': 'plus', 'b': 'int'},
      {'pl': 'Kamień duszy {a} (rodzaj {b}), którego bot nie osadzi',
       'en': 'A spirit stone {a} (kind {b}) the bot cannot seat'}),
 33: ({'a': 'int', 'b': 'int', 'c': 'enum:BOOK_USEFUL'},
      {'pl': 'Księga ogólna: {a} przed nią w plecaku, zapas {b}{c}',
       'en': 'A general book: {a} ahead of it in the bag, keeps {b}{c}'}),
 34: ({}, {'pl': 'Wyceniony z nazwy w arkuszu Iwakury', 'en': "Priced by name on Iwakura's sheet"}),
 35: ({'a': 'skill', 'b': 'int'},
      {'pl': 'Księga ({a}) na ladzie droppera metinów, zapas {b}',
       'en': "A book ({a}) on a Metin dropper's counter, keeps {b}"}),
 36: ({'a': 'skill', 'b': 'int'},
      {'pl': 'Własna księga ({a}) ponad zapas {b}', 'en': 'Its own book ({a}) over the keep of {b}'}),
 37: ({'a': 'skill'}, {'pl': 'Księga innej ścieżki ({a})', 'en': "Another build's book ({a})"}),
 38: ({'a': 'plus'},
      {'pl': 'Zbroja lub biżuteria {a} — towar każdego bota', 'en': "Armour or a jewel at {a} — every bot's goods"}),
 39: ({'a': 'plus'},
      {'pl': 'Słaby ekwipunek {a} na ladzie zbieracza złomu', 'en': "Low gear {a} on a scrap keeper's counter"}),
 40: ({'a': 'int', 'b': 'int'},
      {'pl': 'Nieotwarta szkatułka ponad zapas: {a} w plecaku, zapas {b}',
       'en': 'An unopened chest over the hold: {a} in the bag, holds {b}'}),
 41: ({'a': 'int', 'b': 'int'},
      {'pl': 'Klucz bez skrzyni ponad zapas: {a} w plecaku, zapas {b}',
       'en': 'A key with no chest, over the keep: {a} in the bag, keeps {b}'})}

DECISION_STEPS = {0: (None, {}, {'pl': 'Nieznany krok', 'en': 'Unknown step'}, {'pl': '', 'en': ''}),
 1: ('pct',
     {'a': 'pct', 'b': 'x10000', 'c': 'int'},
     {'pl': 'Kontekst', 'en': 'Context'},
     {'pl': 'krzywa {value}, stawka yang {a}, inflacja {b} (kroków: {c})',
      'en': 'curve {value}, yang rate {a}, inflation {b} ({c} steps)'}),
 2: ('x100',
     {'a': 'apply', 'b': 'applyval:a', 'c': 'enum:AT_TOP'},
     {'pl': 'Linia bonusu', 'en': 'Bonus line'},
     {'pl': '{a} {b}{c}: {value}', 'en': '{a} {b}{c}: {value}'}),
 3: ('x100',
     {'a': 'int'},
     {'pl': 'Linie na maksimum', 'en': 'Lines at the top'},
     {'pl': 'linii na maksimum: {a}, mnożnik {value}', 'en': '{a} lines at the top, multiplier {value}'}),
 4: ('pct',
     {'a': 'x100'},
     {'pl': 'Dopłata za bonusy', 'en': 'Bonus premium'},
     {'pl': 'dopłata {value} (iloczyn z limitem {a})', 'en': 'premium {value} (capped product {a})'}),
 5: ('yang',
     {'a': 'plus'},
     {'pl': 'Wkład u kowala', 'en': "The blacksmith's bill"},
     {'pl': 'kowal dostał {value} za drogę do {a}', 'en': 'the blacksmith was paid {value} on the way to {a}'}),
 6: (None,
     {'a': 'yang', 'b': 'item', 'c': 'plus'},
     {'pl': 'Arkusz Iwakury (ekwipunek)', 'en': "Iwakura's sheet (gear)"},
     {'pl': '{b}, {c}: z arkusza {a}', 'en': '{b}, {c}: sheet price {a}'}),
 7: ('pct',
     {'a': 'int'},
     {'pl': 'Osadzone kamienie', 'en': 'Seated stones'},
     {'pl': 'kamieni: {a}, dopłata {value}', 'en': '{a} stones, premium {value}'}),
 8: (None,
     {'a': 'plus'},
     {'pl': 'Cena stała za plus', 'en': 'Flat price for the plus'},
     {'pl': 'cena stała dla {a}', 'en': 'flat price for {a}'}),
 9: (None,
     {'a': 'yang', 'b': 'x100'},
     {'pl': 'Złom', 'en': 'Scrap'},
     {'pl': 'cena handlarza {a}, mnożnik {b}', 'en': 'merchant price {a}, multiplier {b}'}),
 10: (None,
      {'a': 'yang'},
      {'pl': 'Próg wkładu', 'en': 'Investment floor'},
      {'pl': 'podniesiona do rachunku kowala {a}', 'en': "raised to the blacksmith's bill {a}"}),
 11: (None,
      {'a': 'pct'},
      {'pl': 'Premia za bonusy', 'en': 'Bonus premium applied'},
      {'pl': 'premia {a}', 'en': 'premium {a}'}),
 12: (None,
      {'a': 'pctsigned', 'b': 'enum:PREVIEW'},
      {'pl': 'Konkurencja', 'en': 'Competition'},
      {'pl': 'odchylenie {a}{b}', 'en': 'swing {a}{b}'}),
 13: (None,
      {'a': 'mob', 'b': 'enum:MARBLE_SRC'},
      {'pl': 'Arkusz Iwakury (marmur)', 'en': "Iwakura's sheet (marble)"},
      {'pl': '{a}: {b}', 'en': '{a}: {b}'}),
 14: (None, {'a': 'int'}, {'pl': 'Ilość', 'en': 'Count'}, {'pl': '× {a} szt.', 'en': '× {a}'}),
 15: (None,
      {'a': 'yang', 'b': 'pct'},
      {'pl': 'Punkt wyjścia: handlarz', 'en': 'Starting point: the merchant'},
      {'pl': 'cena handlarza {a}, narzut {b}', 'en': 'merchant price {a}, markup {b}'}),
 16: (None, {}, {'pl': 'Punkt wyjścia: broń 30 lv', 'en': 'Starting point: a level-30 weapon'}, {'pl': '', 'en': ''}),
 17: (None,
      {'a': 'skill', 'b': 'yang'},
      {'pl': 'Arkusz Iwakury (księga)', 'en': "Iwakura's sheet (book)"},
      {'pl': '{a}: z arkusza {b}', 'en': '{a}: sheet price {b}'}),
 18: (None,
      {'a': 'item'},
      {'pl': 'Arkusz Iwakury (księga ogólna)', 'en': "Iwakura's sheet (general book)"},
      {'pl': '{a}', 'en': '{a}'}),
 19: (None,
      {'a': 'yang'},
      {'pl': 'Arkusz Iwakury (materiał)', 'en': "Iwakura's sheet (material)"},
      {'pl': 'z arkusza {a}', 'en': 'sheet price {a}'}),
 20: (None,
      {'a': 'yang', 'b': 'yang'},
      {'pl': 'Wartość szkatułki', 'en': 'Chest worth'},
      {'pl': 'z arkusza {a}, wartość zawartości {b}', 'en': 'sheet {a}, worth by its contents {b}'}),
 21: (None,
      {'a': 'skill'},
      {'pl': 'Arkusz Iwakury (Zwój Zapomnienia)', 'en': "Iwakura's sheet (Forgetting Scroll)"},
      {'pl': '{a}', 'en': '{a}'}),
 22: (None,
      {'a': 'enum:FIXED'},
      {'pl': 'Stała cena wyjściowa', 'en': 'Fixed starting price'},
      {'pl': '{a}', 'en': '{a}'}),
 23: (None,
      {'a': 'plus', 'b': 'int', 'c': 'enum:GRADE_TABLE'},
      {'pl': 'Arkusz Iwakury (kamień duszy)', 'en': "Iwakura's sheet (spirit stone)"},
      {'pl': '{a}, rodzaj {b}{c}', 'en': '{a}, kind {b}{c}'}),
 24: (None, {}, {'pl': 'Brak ceny handlarza', 'en': 'No merchant price'}, {'pl': '', 'en': ''}),
 25: (None,
      {'a': 'yang', 'b': 'permille', 'c': 'pct'},
      {'pl': 'Portfele', 'en': 'Wallets'},
      {'pl': 'mediana portfela {a}, udział {b}, wartość {c}', 'en': 'median wallet {a}, share {b}, worth {c}'}),
 26: ('yang',
      {'a': 'pct'},
      {'pl': 'Limit portfela na stos', 'en': 'Wallet cap for the stack'},
      {'pl': 'limit {value} za sztukę, stos {a}', 'en': 'cap {value} a unit, stack {a}'}),
 27: (None,
      {'a': 'yang', 'b': 'int'},
      {'pl': 'Pamięć sprzedaży', 'en': 'Sale memory'},
      {'pl': 'mediana zapłaconej ceny {a}, sprzedaży: {b}', 'en': 'median paid {a}, {b} sales'}),
 28: (None,
      {'a': 'int', 'b': 'int', 'c': 'x100'},
      {'pl': 'Rejestr rynku', 'en': 'Market ledger'},
      {'pl': 'brakuje {a} botom, na ladach {b} szt., mnożnik {c}',
       'en': '{a} bots short, {b} units on counters, multiplier {c}'}),
 29: (None, {'a': 'yang'}, {'pl': 'Ogranicznik kroku', 'en': 'Step limit'}, {'pl': 'chciał {a}', 'en': 'wanted {a}'}),
 30: (None, {'a': 'pct'}, {'pl': 'Rozrzut sprzedawcy', 'en': "The keeper's spread"}, {'pl': '{a}', 'en': '{a}'}),
 31: (None,
      {'a': 'yang'},
      {'pl': 'Próg dla towaru z bonusem', 'en': 'Floor for bonus goods'},
      {'pl': 'próg {a} za sztukę', 'en': 'floor {a} a unit'}),
 32: (None, {}, {'pl': 'Zaokrąglenie', 'en': 'Rounded'}, {'pl': '', 'en': ''}),
 33: (None,
      {'a': 'pct'},
      {'pl': 'Zniżka biedaka', 'en': "A poor bot's discount"},
      {'pl': 'zniżka {a}', 'en': 'discount {a}'}),
 34: (None,
      {'a': 'int', 'b': 'enum:CLOCK_UNIT', 'c': 'enum:CLOCK_RESTART'},
      {'pl': 'Zegar przeceny', 'en': 'Markdown clock'},
      {'pl': '{a} {b}{c}', 'en': '{a} {b}{c}'}),
 35: (None, {'a': 'pct'}, {'pl': 'Przecena', 'en': 'Markdown'}, {'pl': 'obniżka {a}', 'en': 'down {a}'}),
 36: (None,
      {'a': 'pct', 'b': 'pct', 'c': 'int'},
      {'pl': 'Podwyżka', 'en': 'Markup'},
      {'pl': 'podwyżka {a}: brakowało w {b} przeglądów, sprzedanych linii {c}',
       'en': 'up {a}: missing in {b} of looks, {c} lines sold'}),
 37: (None,
      {'a': 'pct'},
      {'pl': 'Podwyżka odrzucona', 'en': 'Markup refused'},
      {'pl': '{a} przekroczyłoby limit yang', 'en': '{a} would pass the yang limit'}),
 38: (None,
      {'a': 'yang'},
      {'pl': 'Próg wystawienia', 'en': 'Listing floor'},
      {'pl': 'podniesiona do progu {a}', 'en': 'raised to the floor {a}'}),
 39: (None, {'a': 'yang'}, {'pl': 'Pomyłka w cenie', 'en': 'Price slip'}, {'pl': 'miało być {a}', 'en': 'meant {a}'}),
 40: (None, {'a': 'enum:GENERATION'}, {'pl': 'Pokolenie cen', 'en': 'Price generation'}, {'pl': '{a}', 'en': '{a}'}),
 41: (None,
      {'a': 'yang', 'b': 'minutes', 'c': 'enum:SLIP_BY'},
      {'pl': 'Pomyłka poprawiona', 'en': 'Slip put right'},
      {'pl': 'było {a} przez {b}; {c}', 'en': 'was {a} for {b}; {c}'}),
 42: (None,
      {'a': 'yang'},
      {'pl': 'Podniesione do progu', 'en': 'Raised to the floor'},
      {'pl': 'było {a}', 'en': 'was {a}'})}

DECISION_CODE_NAMES = {'EVENT': {1: 'EVENT_LIST_CREATE',
           2: 'EVENT_LIST_ADD',
           3: 'EVENT_LIST_CLASSIC',
           4: 'EVENT_REPRICE',
           5: 'EVENT_SLIP_FIX',
           6: 'EVENT_SLIP_FIX_CORE',
           7: 'EVENT_RAISE_TO_FLOOR',
           8: 'EVENT_TAKE_OFF',
           9: 'EVENT_RECLAIM',
           10: 'EVENT_SOLD'},
 'GOODS': {0: 'GOODS_UNKNOWN',
           1: 'GOODS_POLICY_STALL',
           2: 'GOODS_GAMBLE_GOODS',
           3: 'GOODS_GM_STONE_SPARE',
           4: 'GOODS_MARBLE',
           5: 'GOODS_METIN_DETECTOR',
           6: 'GOODS_CATACOMB_HEAD',
           7: 'GOODS_BONUS_STONE_SPARE',
           8: 'GOODS_FORGET_SCROLL_MERCHANT_ONLY',
           9: 'GOODS_STALKI_OTHER',
           10: 'GOODS_LEVEL30_SALE_READY',
           11: 'GOODS_LEVEL30_NOT_KEPT',
           12: 'GOODS_LOW_LEVEL_LOW_PLUS',
           13: 'GOODS_LOW_LEVEL_REFINED',
           14: 'GOODS_LPP_SURPLUS',
           15: 'GOODS_VALUABLE_BONUS',
           16: 'GOODS_MERCHANT_ONLY_GEAR',
           17: 'GOODS_PRECIOUS_SPARE',
           18: 'GOODS_SAFE_SCROLL_OVER_KEEP',
           19: 'GOODS_HORSE_MEDAL',
           20: 'GOODS_MATERIAL_FLOOR',
           21: 'GOODS_MATERIAL_SHORT',
           22: 'GOODS_MATERIAL_OTHER',
           23: 'GOODS_PICKUP_GOODS',
           24: 'GOODS_SURPLUS_POTION',
           25: 'GOODS_SURPLUS_RECIPE',
           26: 'GOODS_HAIR_DYE_SHOP',
           27: 'GOODS_HAIR_DYE_FISHED_KEPT',
           28: 'GOODS_ISHOP_HAIRSTYLE',
           29: 'GOODS_FORGET_SCROLL',
           30: 'GOODS_MAGIC_DUST',
           31: 'GOODS_SOUL_STONE_LOW_MARKET',
           32: 'GOODS_SOUL_STONE',
           33: 'GOODS_GENERAL_BOOK',
           34: 'GOODS_SHEET_GOODS',
           35: 'GOODS_SKILL_BOOK_DROPPER',
           36: 'GOODS_SKILL_BOOK_OWN_SPARE',
           37: 'GOODS_SKILL_BOOK_OTHER_CLASS',
           38: 'GOODS_LOW_PLUS_GEAR',
           39: 'GOODS_SCRAP_KEEPER_LOW',
           40: 'GOODS_SURPLUS_CHEST',
           41: 'GOODS_SURPLUS_KEY'},
 'SHAPE': {0: 'SHAPE_WHOLE_STACK',
           1: 'SHAPE_NATURAL_LINE',
           2: 'SHAPE_POTION_PACK',
           3: 'SHAPE_DUST_PACK',
           4: 'SHAPE_MEDAL_PAIR',
           5: 'SHAPE_COUNTED_SINGLE',
           6: 'SHAPE_KEY_SINGLE',
           7: 'SHAPE_CHEST_PACK',
           8: 'SHAPE_CLASSIC_SPLIT_SINGLE'},
 'OFF': {1: 'OFF_LPP',
         2: 'OFF_SOUL_STONE_DUST',
         3: 'OFF_MARBLE',
         4: 'OFF_SAME_VNUM',
         5: 'OFF_MISSION_BOOKS',
         6: 'OFF_JUNK_WEAPON',
         7: 'OFF_POTION_PACK',
         8: 'OFF_LOW_ARMOUR',
         9: 'OFF_LOW_JEWEL',
         10: 'OFF_HAIR_DYE',
         11: 'OFF_LEVEL30_ANVIL',
         12: 'OFF_CHEST_PACK',
         13: 'OFF_GM_STONE',
         14: 'OFF_SCROLL_PACK',
         15: 'OFF_MEDAL_PACK',
         16: 'OFF_HEAP_PACK',
         17: 'OFF_MATERIAL_PACK',
         18: 'OFF_LOW_GEAR',
         19: 'OFF_TACKLE',
         20: 'OFF_RECLAIM_TO_WEAR'},
 'STEP': {1: 'STEP_CONTEXT',
          2: 'STEP_BONUS_LINE',
          3: 'STEP_BONUS_MAX_LINES',
          4: 'STEP_BONUS_PERCENT',
          5: 'STEP_INVESTMENT',
          6: 'STEP_SHEET_GEAR',
          7: 'STEP_SOCKET_STONES',
          8: 'STEP_FLAT_PLUS',
          9: 'STEP_SCRAP',
          10: 'STEP_INVESTMENT_FLOOR',
          11: 'STEP_BONUS_PREMIUM',
          12: 'STEP_COMPETITION',
          13: 'STEP_SHEET_MARBLE',
          14: 'STEP_COUNT',
          15: 'STEP_PRIOR_MERCHANT',
          16: 'STEP_PRIOR_LEVEL30',
          17: 'STEP_SHEET_BOOK',
          18: 'STEP_SHEET_GENERAL_BOOK',
          19: 'STEP_SHEET_MATERIAL',
          20: 'STEP_CHEST_WORTH',
          21: 'STEP_SHEET_FORGET_SCROLL',
          22: 'STEP_FIXED_PRIOR',
          23: 'STEP_SHEET_SOUL_STONE',
          24: 'STEP_NO_MERCHANT_PRIOR',
          25: 'STEP_WALLET',
          26: 'STEP_WALLET_STACK_CAP',
          27: 'STEP_SALE_MEMORY',
          28: 'STEP_LEDGER',
          29: 'STEP_STEP_LIMIT',
          30: 'STEP_SPREAD',
          31: 'STEP_BONUS_GOODS_FLOOR',
          32: 'STEP_ROUND',
          33: 'STEP_POOR_DISCOUNT',
          34: 'STEP_MARKDOWN_CLOCK',
          35: 'STEP_MARKDOWN',
          36: 'STEP_MARKUP',
          37: 'STEP_MARKUP_REFUSED',
          38: 'STEP_LISTING_FLOOR',
          39: 'STEP_SLIP',
          40: 'STEP_GENERATION',
          41: 'STEP_SLIP_PUT_RIGHT',
          42: 'STEP_RAISED_TO_FLOOR'},
 'LFLAG': {1: 'LFLAG_UNDER_MERCHANT',
           2: 'LFLAG_FLOOR_BOUND',
           4: 'LFLAG_UNDER_SHEET_HALF',
           8: 'LFLAG_OVER_SHEET_3X',
           16: 'LFLAG_MEMORY_PULL',
           32: 'LFLAG_REGULATOR_EDGE',
           64: 'LFLAG_MARKDOWN_MAX',
           128: 'LFLAG_MARKUP_MAX',
           256: 'LFLAG_SLIP',
           512: 'LFLAG_BETTER_THAN_WORN_SOON',
           1024: 'LFLAG_LOW_RANK',
           2048: 'LFLAG_PRICE_JUMP'},
 'PATH': {1: 'PATH_EQUIP_PASS',
          2: 'PATH_EMPTY_HAND',
          3: 'PATH_EMERGENCY_BUY',
          4: 'PATH_PROFESSION_OFF',
          5: 'PATH_UNIQUE'},
 'RULE': {1: 'RULE_SCORE_UPGRADE',
          2: 'RULE_EMPTY_SLOT',
          3: 'RULE_OWNER_PIN',
          4: 'RULE_OLD_LOW_WEAPON_BANNED',
          5: 'RULE_ARCHER_STONE_SWITCH',
          6: 'RULE_EMPTY_HAND_BEST',
          7: 'RULE_EMPTY_HAND_LOW_FALLBACK',
          8: 'RULE_EMERGENCY_WEAPON',
          9: 'RULE_PROFESSION_MISMATCH',
          10: 'RULE_UNIQUE_NEVER_WORN'},
 'CONTEXT': {0: 'CONTEXT_NONE',
             1: 'CONTEXT_AFTER_BLACKSMITH',
             2: 'CONTEXT_AFTER_BURN',
             3: 'CONTEXT_AFTER_SPAWN',
             4: 'CONTEXT_RETURNED_FROM_COUNTER',
             5: 'CONTEXT_WENT_TO_COUNTER'},
 'ORIGIN': {0: 'ORIGIN_UNKNOWN',
            1: 'ORIGIN_NPC_LADDER',
            2: 'ORIGIN_NPC_EMERGENCY',
            3: 'ORIGIN_NPC_PROPER_WEAPON',
            4: 'ORIGIN_REFINED',
            5: 'ORIGIN_RECLAIMED',
            6: 'ORIGIN_SAFEBOX',
            7: 'ORIGIN_GAMBLER'},
 'ROLE': {1: 'ROLE_LEVEL30_FAMILY',
          2: 'ROLE_CLASS_LEVEL30',
          4: 'ROLE_LEVEL30_PROJECT',
          8: 'ROLE_LINES_PROJECT',
          16: 'ROLE_STALKI',
          32: 'ROLE_STALKI_KEPT',
          64: 'ROLE_HIGHER_TIER_SPARE',
          128: 'ROLE_BACKUP',
          256: 'ROLE_SCROLL_RULE_PIECE',
          512: 'ROLE_PRIZE',
          1024: 'ROLE_LISTED_JEWEL',
          2048: 'ROLE_SOUL_STONES',
          4096: 'ROLE_GAMBLE_SET',
          8192: 'ROLE_OWNER_PINNED',
          16384: 'ROLE_BANNED_LOW_WEAPON',
          32768: 'ROLE_SCROLL_ONLY_WEAPON'},
 'TERM': {1: 'TERM_TOTAL',
          2: 'TERM_BLOW_X1000',
          3: 'TERM_CLASS_PREF',
          4: 'TERM_DEFENCE_X1000',
          5: 'TERM_LEVEL_TIE',
          6: 'TERM_PROTO_APPLIES',
          7: 'TERM_LINES',
          8: 'TERM_SOUL_STONES',
          9: 'TERM_IMMUNE',
          10: 'TERM_RACE_LINES',
          11: 'TERM_TIER_PCT',
          12: 'TERM_LISTED_JEWEL_PCT',
          13: 'TERM_BOOTS_FAMILY',
          14: 'TERM_LEVEL_LIMIT',
          15: 'TERM_PLUS',
          20: 'TERM_BLOW',
          21: 'TERM_ROLL',
          22: 'TERM_MAGIC_ROLL',
          23: 'TERM_PLUS_ATTACK',
          24: 'TERM_GRADE',
          25: 'TERM_ATT_PCT',
          26: 'TERM_RACE_PCT',
          27: 'TERM_AVG_PCT',
          28: 'TERM_SKILL_PCT',
          29: 'TERM_CRIT_PCT',
          30: 'TERM_PEN_PCT',
          31: 'TERM_LEVEL_BONUS_PCT',
          32: 'TERM_ATTACK',
          33: 'TERM_MOB_DEFENCE',
          34: 'TERM_HIT',
          35: 'TERM_SKILL_HIT',
          36: 'TERM_STYLE',
          37: 'TERM_HIT_SHARE',
          38: 'TERM_SKILL_SHARE',
          40: 'TERM_LINES_TIERED'},
 'EFLAG': {1: 'EFLAG_PLUS_DOWN',
           2: 'EFLAG_LEVEL_DOWN',
           4: 'EFLAG_LINES_WORSE',
           8: 'EFLAG_SMALL_GAIN',
           16: 'EFLAG_FLIP_FLOP',
           32: 'EFLAG_OLD_ZEROED',
           64: 'EFLAG_PROJECT_REPLACED',
           128: 'EFLAG_SUPPRESSED_BEFORE',
           256: 'EFLAG_AFTER_BURN'}}

