# MT2009_PLUS_MONSTER_CARDS_V1 - Karty Potworow: the Polish texts of the window (Autor: Digi Rasta,
# his translation of the package's Turkish texts, karty_teksty.py). Python 2.7; Polish letters as
# CP1250 escapes.

GRA = {
	"MC_ACCUMULATION_COUNT": "Zebrane karty potwora: %d",
	"MC_ACHIEV_NAME": "%s (%d)",
	"MC_ACHIEV_REGIST_ABLE": "Spe\xb3niasz warunki bonusu zestawu %s (gwiazdki: %d).",
	"MC_ACHIEV_REGIST_FAIL": "Teraz nie mo\xbfesz zg\xb3osi\xe6 bonusu zestawu.",
	"MC_ACHIEV_REGIST_FAIL_CHECK_COUNT": "Nie mo\xbfesz zg\xb3osi\xe6 bonusu. Zamknij okno i spr\xf3buj ponownie!",
	"MC_ACHIEV_REGIST_QUESTION_1": "Czy chcesz zg\xb3osi\xe6 bonus zestawu %s? Zu\xbfyje to gwiazdki potwor\xf3w zestawu (potwor\xf3w: %d).",
	"MC_ACHIEV_REGIST_QUESTION_2": "Wyboru nie mo\xbfna cofn\xb9\xe6. Kontynuowa\xe6?",
	"MC_ACHIEV_SHOW_APPLYS": "Poka\xbf stan",
	"MC_ACHIEV_SHOW_MONSTER": "Poka\xbf obraz",
	"MC_ALTER_TEXT": "Poziom misji %d",
	"MC_CARD_FALL_SHORT": "Za ma\xb3o zebranych kart.",
	"MC_CARD_SHUFFLE": "Czy chcesz wylosowa\xe6 nowe cele misji (zu\xbfyje Kart\xea Nowego Uk\xb3adu)?",
	"MC_INIT_ITEM_FALL_SHORT": "Potrzebujesz %d Kart Nowego Pocz\xb9tku.",
	"MC_MISSION_FAIL_MSG": "Brak aktywnej misji albo limit zosta\xb3 przekroczony.",
	"MC_MISSION_INIT": "Czy chcesz cofn\xb9\xe6 misj\xea do poziomu 1?",
	"MC_MISSION_NO_CLEAR": "Najpierw uko\xf1cz misj\xea.",
	"MC_MOTION_BUTTON_OVER_MSG": "Ta opcja jest dost\xeapna od 2. gwiazdki.",
	"MC_POLY_BUTTON_OVER_MSG": "Ta opcja jest dost\xeapna od 3. gwiazdki.",
	"MC_POLY_FAIL": "Teraz nie mo\xbfesz zmieni\xe6 si\xea w potwora.",
	"MC_POLY_QUESTION": "Czy chcesz zmieni\xe6 si\xea w tego potwora?",
	"MC_PROMOTION_MAX": "Wi\xeacej ulepsze\xf1 nie ma.",
	"MC_PROMOTION_QUESTION": "Czy chcesz podnie\x9c\xe6 poziom?",
	"MC_QUESTION_BUTTON_DESC1": "Pierwszy reset misji w ci\xb9gu 24 godzin jest darmowy.",
	"MC_QUESTION_BUTTON_DESC2": "Ka\xbfdy kolejny reset wymaga Karty Nowego Pocz\xb9tku.",
	"MC_QUESTION_BUTTON_DESC3": "Kliknij, aby zobaczy\xe6 pozosta\xb3y czas odnowienia.",
	"MC_REWARD_FAIL": "Brak miejsca w ekwipunku.",
	"MC_REWARD_MISSION": "Czy chcesz teraz odebra\xe6 Kart\xea Potwora?",
	"MC_SHUFFLE_NO_ITEM": "Nie masz Karty Nowego Uk\xb3adu.",
	"MC_TIME": "Czas odnowienia: %s",
	"MC_TRADE_QUESTION": "Zostanie zu\xbfytych %d kart z kolekcji. Kontynuowa\xe6?",
	"MC_USE_ITEM_FAIL": "Tej karty nie mo\xbfna doda\xe6.",
	"MC_USE_ITEM_QUESTION": "Czy chcesz doda\xe6 t\xea kart\xea potwora?",
	"MC_WARP_BUTTON_OVER_MSG": "Ta opcja jest dost\xeapna od 4. gwiazdki.",
	"MC_WARP_FAIL": "Nie mo\xbfesz si\xea teraz teleportowa\xe6.",
	"MC_WARP_LIMIT_LEVEL": "Tw\xf3j poziom jest za niski, by si\xea teleportowa\xe6.",
	"MC_WARP_QUESTION": "Czy chcesz teleportowa\xe6 si\xea w rejon tego potwora?",
}

INTERFEJS = {
	"KEYCHANGE_MONSTER_CARD_WINDOW": "Karty Potwor\xf3w",
	"MC_ACHIEV_ABLE_REGIST": "Zg\xb3o\x9c",
	"MC_ACHIEV_APPLY": "Zastosuj",
	"MC_ACHIEV_APPLYING": "Aktywny",
	"MC_ACHIEV_BONUS_NONE": "Brak bonusu",
	"MC_ACHIEV_DISABLE": "Nieaktywny",
	"MC_ACHIEV_DUNGEON": "Zestawy lochowe",
	"MC_ACHIEV_DUNGEON_BONUS": "Bonus lochowy",
	"MC_ACHIEV_FIELD": "Zestawy polowe",
	"MC_ACHIEV_FIELD_BONUS": "Bonus polowy",
	"MC_ACHIEV_REGIST": "Zg\xb3o\x9c bonus zestawu",
	"MC_ACHIEV_SHOW": "Szczeg\xf3\xb3y",
	"MC_ACHIEV_SORT_ABLE_REGIST": "Do zg\xb3oszenia",
	"MC_ACHIEV_SORT_ALL": "Wszystkie",
	"MC_ACHIEV_SORT_APPLYING": "Aktywne",
	"MC_ACHIEV_SORT_DISABLE": "Nieosi\xb9gni\xeate",
	"MC_ACHIEV_SORT_REGIST": "Mo\xbfliwe do w\xb3\xb9czenia",
	"MC_EXCHANGE_BUTTON": "Wymie\xf1",
	"MC_MISSION_INIT_BUTTON": "Zresetuj poziom misji",
	"MC_MOTION_BUTTON": "Ruch",
	"MC_POLY_BUTTON": "Przemie\xf1",
	"MC_PROMOTION_BUTTON": "Ulepsz",
	"MC_REQUEST_MISSION_BUTTON": "Przyjmij misj\xea",
	"MC_REWARD_CARD_BUTTON": "Odbierz kart\xea potwora",
	"MC_SHUFFLE_BUTTON": "Wylosuj cele od nowa",
	"MC_SUMMON_BUTTON": "Przywo\xb3aj",
	"MC_TAB_BUTTON_ACHIEV": "Bonusy zestaw\xf3w",
	"MC_TAB_BUTTON_CARD_MISSION": "Misja kart",
	"MC_TAB_BUTTON_PARTY": "Kolekcja loch\xf3w",
	"MC_TAB_BUTTON_SOLO": "Kolekcja p\xf3l",
	"MC_WARP_BUTTON": "Teleport",
	"MONSTER_CARD_ACHIEV_BONUS": "Bonusy zestaw\xf3w",
}

KOMUNIKATY = {
	"COOLDOWN": "Funkcja b\xeadzie dost\xeapna za: %s.",
	"DROP_HEADER": "Drop potwora %s:",
	"DROP_MORE": "  ...i jeszcze %d - pe\xb3na lista w oknie Drop wiki (pasek boczny ekwipunku).",
	"DROP_ROW": "  %s x%s (%s%%)",
	"DISABLED": "Karty Potwor\xf3w s\xb9 wy\xb3\xb9czone na tym serwerze.",
	"MOB_IS_ALREADY_DEAD": "Przywo\xb3any potw\xf3r ju\xbf nie \xbfyje.",
	"NEED_STAGE": "Ta funkcja wymaga co najmniej %d gwiazdek.",
	"NOT_ALL_MONSTERS_KILLED": "Najpierw pokonaj wszystkie cele misji.",
	"NOT_ENOUGH_FOR_TRADE": "Za ma\xb3o kart do wymiany.",
	"NO_NEW_MISSION": "Masz ju\xbf cele misji.",
	"NO_PROMOTION": "Za ma\xb3o kart, by awansowa\xe6 potwora.",
	"PLAYER_DONT_EXIST": "Nie ma takiego gracza.",
	"RANK_STARS": "Wybrana ranga wymaga tylu gwiazdek u ka\xbfdego potwora zestawu.",
}
